# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'stack_dashboardLwgRlT.ui'
##
## Created by: Qt User Interface Compiler version 6.1.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1200, 800)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.stackedWidget = QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(0, 0, 1200, 800))
        self.stackedWidget.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.dashboard = QWidget()
        self.dashboard.setObjectName(u"dashboard")
        self.anaFrameGosterge = QFrame(self.dashboard)
        self.anaFrameGosterge.setObjectName(u"anaFrameGosterge")
        self.anaFrameGosterge.setGeometry(QRect(0, 0, 1200, 800))
        self.anaFrameGosterge.setStyleSheet(u"background-color: rgb(6, 6, 58);\n"
"")
        self.anaFrameGosterge.setFrameShape(QFrame.NoFrame)
        self.anaFrameGosterge.setFrameShadow(QFrame.Raised)
        self.yagFrame_3 = QFrame(self.anaFrameGosterge)
        self.yagFrame_3.setObjectName(u"yagFrame_3")
        self.yagFrame_3.setGeometry(QRect(40, 620, 270, 270))
        self.yagFrame_3.setStyleSheet(u"background-color:none;")
        self.yagFrame_3.setFrameShape(QFrame.NoFrame)
        self.yagFrame_3.setFrameShadow(QFrame.Raised)
        self.yagGradient_3 = QFrame(self.yagFrame_3)
        self.yagGradient_3.setObjectName(u"yagGradient_3")
        self.yagGradient_3.setGeometry(QRect(10, 20, 240, 240))
        self.yagGradient_3.setStyleSheet(u"border-radius: 120px;\n"
"background-color: qlineargradient(spread:pad, x1:0.999873, y1:0.239, x2:0, y2:0.086, stop:0 rgba(104, 1, 174, 255), stop:1 rgba(200, 107, 92, 255));\n"
"background-color: qlineargradient(spread:pad, x1:0.761, y1:0.494591, x2:0.024, y2:0.261, stop:0 rgba(215, 88, 52, 255), stop:0.709742 rgba(249, 162, 72, 255));")
        self.yagGradient_3.setFrameShape(QFrame.NoFrame)
        self.yagGradient_3.setFrameShadow(QFrame.Raised)
        self.kapak1_3 = QFrame(self.yagFrame_3)
        self.kapak1_3.setObjectName(u"kapak1_3")
        self.kapak1_3.setGeometry(QRect(0, 130, 260, 130))
        self.kapak1_3.setStyleSheet(u"background-color: rgb(6, 6, 58);")
        self.kapak1_3.setFrameShape(QFrame.NoFrame)
        self.kapak1_3.setFrameShadow(QFrame.Raised)
        self.yagFrameIc_3 = QFrame(self.yagFrame_3)
        self.yagFrameIc_3.setObjectName(u"yagFrameIc_3")
        self.yagFrameIc_3.setGeometry(QRect(20, 30, 220, 220))
        self.yagFrameIc_3.setStyleSheet(u"background-color: rgb(6, 6, 58);\n"
"border-radius: 110px;")
        self.yagFrameIc_3.setFrameShape(QFrame.NoFrame)
        self.yagFrameIc_3.setFrameShadow(QFrame.Raised)
        self.yagFrameOn_3 = QFrame(self.yagFrame_3)
        self.yagFrameOn_3.setObjectName(u"yagFrameOn_3")
        self.yagFrameOn_3.setGeometry(QRect(60, 70, 140, 140))
        self.yagFrameOn_3.setStyleSheet(u"background-color: rgb(3, 2, 34);\n"
"border-radius:70px;")
        self.yagFrameOn_3.setFrameShape(QFrame.NoFrame)
        self.yagFrameOn_3.setFrameShadow(QFrame.Raised)
        self.yag_3 = QLabel(self.yagFrameOn_3)
        self.yag_3.setObjectName(u"yag_3")
        self.yag_3.setGeometry(QRect(70, 40, 71, 21))
        self.yag_3.setStyleSheet(u"color: #ffffff; background-color: none")
        self.yag_3.setAlignment(Qt.AlignCenter)
        self.yagIcon_3 = QLabel(self.yagFrameOn_3)
        self.yagIcon_3.setObjectName(u"yagIcon_3")
        self.yagIcon_3.setGeometry(QRect(15, 25, 40, 35))
        self.yagIcon_3.setStyleSheet(u"background-color: none;")
        self.yagIcon_3.setPixmap(QPixmap(u"tba.png"))
        self.yagIcon_3.setScaledContents(True)
        self.yagProgress_3 = QFrame(self.yagFrame_3)
        self.yagProgress_3.setObjectName(u"yagProgress_3")
        self.yagProgress_3.setGeometry(QRect(30, 40, 200, 200))
        self.yagProgress_3.setStyleSheet(u"background-color: qconicalgradient(cx:0.5, cy:0.5, angle:180, stop:0.801158 rgba(85, 170, 255, 0), stop:0.803089 rgba(249, 201, 111, 255));\n"
"border-radius: 100px;")
        self.yagProgress_3.setFrameShape(QFrame.NoFrame)
        self.yagProgress_3.setFrameShadow(QFrame.Raised)
        self.yagGolge_3 = QFrame(self.yagProgress_3)
        self.yagGolge_3.setObjectName(u"yagGolge_3")
        self.yagGolge_3.setGeometry(QRect(10, 10, 180, 180))
        self.yagGolge_3.setStyleSheet(u"border-radius: 90px;\n"
"background-color: rgba(0, 0, 0,150);\n"
"border-width: 2px;\n"
"border-style: solid;")
        self.yagGolge_3.setFrameShape(QFrame.NoFrame)
        self.yagGolge_3.setFrameShadow(QFrame.Raised)
        self.labelY0_3 = QLabel(self.yagFrame_3)
        self.labelY0_3.setObjectName(u"labelY0_3")
        self.labelY0_3.setGeometry(QRect(-3, 80, 20, 20))
        self.labelY0_3.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: none;")
        self.labelY0_3.setAlignment(Qt.AlignCenter)
        self.labelY2_3 = QLabel(self.yagFrame_3)
        self.labelY2_3.setObjectName(u"labelY2_3")
        self.labelY2_3.setGeometry(QRect(30, 20, 20, 20))
        self.labelY2_3.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: none;")
        self.labelY2_3.setAlignment(Qt.AlignCenter)
        self.labelY4_3 = QLabel(self.yagFrame_3)
        self.labelY4_3.setObjectName(u"labelY4_3")
        self.labelY4_3.setGeometry(QRect(115, -1, 20, 20))
        self.labelY4_3.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: none;")
        self.labelY4_3.setAlignment(Qt.AlignCenter)
        self.labelY6_3 = QLabel(self.yagFrame_3)
        self.labelY6_3.setObjectName(u"labelY6_3")
        self.labelY6_3.setGeometry(QRect(200, 20, 20, 20))
        self.labelY6_3.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: none;")
        self.labelY6_3.setAlignment(Qt.AlignCenter)
        self.labelY8_3 = QLabel(self.yagFrame_3)
        self.labelY8_3.setObjectName(u"labelY8_3")
        self.labelY8_3.setGeometry(QRect(240, 80, 20, 20))
        self.labelY8_3.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: none;")
        self.labelY8_3.setAlignment(Qt.AlignCenter)
        self.yagGradient_3.raise_()
        self.yagFrameIc_3.raise_()
        self.labelY0_3.raise_()
        self.labelY2_3.raise_()
        self.labelY4_3.raise_()
        self.labelY6_3.raise_()
        self.labelY8_3.raise_()
        self.yagProgress_3.raise_()
        self.yagFrameOn_3.raise_()
        self.kapak1_3.raise_()
        self.hararetFrame_3 = QFrame(self.anaFrameGosterge)
        self.hararetFrame_3.setObjectName(u"hararetFrame_3")
        self.hararetFrame_3.setGeometry(QRect(326, 620, 270, 270))
        self.hararetFrame_3.setStyleSheet(u"background-color:none;")
        self.hararetFrame_3.setFrameShape(QFrame.NoFrame)
        self.hararetFrame_3.setFrameShadow(QFrame.Raised)
        self.hararetGradient_3 = QFrame(self.hararetFrame_3)
        self.hararetGradient_3.setObjectName(u"hararetGradient_3")
        self.hararetGradient_3.setGeometry(QRect(10, 20, 240, 240))
        self.hararetGradient_3.setStyleSheet(u"background-color: qlineargradient(spread:pad, x1:0.488, y1:0, x2:0.505, y2:0.688, stop:0 rgba(104, 1, 174, 255), stop:1 rgba(200, 107, 92, 255));\n"
"background-color: qlineargradient(spread:pad, x1:0.761, y1:0.494591, x2:0.024, y2:0.261, stop:0 rgba(215, 88, 52, 255), stop:0.709742 rgba(249, 162, 72, 255));\n"
"border-radius: 120px;")
        self.hararetGradient_3.setFrameShape(QFrame.NoFrame)
        self.hararetGradient_3.setFrameShadow(QFrame.Raised)
        self.kapak2_3 = QFrame(self.hararetFrame_3)
        self.kapak2_3.setObjectName(u"kapak2_3")
        self.kapak2_3.setGeometry(QRect(0, 130, 260, 130))
        self.kapak2_3.setStyleSheet(u"background-color: rgb(6, 6, 58);")
        self.kapak2_3.setFrameShape(QFrame.NoFrame)
        self.kapak2_3.setFrameShadow(QFrame.Raised)
        self.hararetFrameIc_3 = QFrame(self.hararetFrame_3)
        self.hararetFrameIc_3.setObjectName(u"hararetFrameIc_3")
        self.hararetFrameIc_3.setGeometry(QRect(20, 30, 220, 220))
        self.hararetFrameIc_3.setStyleSheet(u"background-color: rgb(6, 6, 58);\n"
"border-radius: 110px;")
        self.hararetFrameIc_3.setFrameShape(QFrame.NoFrame)
        self.hararetFrameIc_3.setFrameShadow(QFrame.Raised)
        self.hararetFrameOn_3 = QFrame(self.hararetFrame_3)
        self.hararetFrameOn_3.setObjectName(u"hararetFrameOn_3")
        self.hararetFrameOn_3.setGeometry(QRect(60, 70, 140, 140))
        self.hararetFrameOn_3.setStyleSheet(u"background-color: rgb(3, 2, 34);\n"
"border-radius:70px;")
        self.hararetFrameOn_3.setFrameShape(QFrame.NoFrame)
        self.hararetFrameOn_3.setFrameShadow(QFrame.Raised)
        self.hararet_3 = QLabel(self.hararetFrameOn_3)
        self.hararet_3.setObjectName(u"hararet_3")
        self.hararet_3.setGeometry(QRect(70, 40, 71, 21))
        self.hararet_3.setStyleSheet(u"color: #ffffff; background-color: none")
        self.hararet_3.setAlignment(Qt.AlignCenter)
        self.hararetIcon_3 = QLabel(self.hararetFrameOn_3)
        self.hararetIcon_3.setObjectName(u"hararetIcon_3")
        self.hararetIcon_3.setGeometry(QRect(15, 25, 40, 35))
        self.hararetIcon_3.setStyleSheet(u"background-color: none;")
        self.hararetIcon_3.setPixmap(QPixmap(u"tba2.png"))
        self.hararetIcon_3.setScaledContents(True)
        self.hararetProgress_3 = QFrame(self.hararetFrame_3)
        self.hararetProgress_3.setObjectName(u"hararetProgress_3")
        self.hararetProgress_3.setGeometry(QRect(30, 40, 200, 200))
        self.hararetProgress_3.setStyleSheet(u"background-color: qconicalgradient(cx:0.5, cy:0.5, angle:180, stop:0.011158 rgba(85, 170, 255, 0), stop:0.013089 rgba(249, 201, 111, 255));\n"
"border-radius: 100px;")
        self.hararetProgress_3.setFrameShape(QFrame.NoFrame)
        self.hararetProgress_3.setFrameShadow(QFrame.Raised)
        self.hararetGolge_3 = QFrame(self.hararetProgress_3)
        self.hararetGolge_3.setObjectName(u"hararetGolge_3")
        self.hararetGolge_3.setGeometry(QRect(10, 10, 180, 180))
        self.hararetGolge_3.setStyleSheet(u"border-radius: 90px;\n"
"background-color: rgba(0, 0, 0,150);\n"
"border-width: 2px;\n"
"border-style: solid;")
        self.hararetGolge_3.setFrameShape(QFrame.NoFrame)
        self.hararetGolge_3.setFrameShadow(QFrame.Raised)
        self.labelH6_3 = QLabel(self.hararetFrame_3)
        self.labelH6_3.setObjectName(u"labelH6_3")
        self.labelH6_3.setGeometry(QRect(203, 21, 20, 20))
        self.labelH6_3.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: none;")
        self.labelH6_3.setAlignment(Qt.AlignCenter)
        self.labelH2_3 = QLabel(self.hararetFrame_3)
        self.labelH2_3.setObjectName(u"labelH2_3")
        self.labelH2_3.setGeometry(QRect(33, 21, 20, 20))
        self.labelH2_3.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: none;")
        self.labelH2_3.setAlignment(Qt.AlignCenter)
        self.labelH0_3 = QLabel(self.hararetFrame_3)
        self.labelH0_3.setObjectName(u"labelH0_3")
        self.labelH0_3.setGeometry(QRect(0, 81, 20, 20))
        self.labelH0_3.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: none;")
        self.labelH0_3.setAlignment(Qt.AlignCenter)
        self.labelH8_3 = QLabel(self.hararetFrame_3)
        self.labelH8_3.setObjectName(u"labelH8_3")
        self.labelH8_3.setGeometry(QRect(243, 81, 20, 20))
        self.labelH8_3.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: none;")
        self.labelH8_3.setAlignment(Qt.AlignCenter)
        self.labelH4_3 = QLabel(self.hararetFrame_3)
        self.labelH4_3.setObjectName(u"labelH4_3")
        self.labelH4_3.setGeometry(QRect(118, 0, 20, 20))
        self.labelH4_3.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: none;")
        self.labelH4_3.setAlignment(Qt.AlignCenter)
        self.hararetGradient_3.raise_()
        self.hararetFrameIc_3.raise_()
        self.labelH6_3.raise_()
        self.labelH2_3.raise_()
        self.labelH0_3.raise_()
        self.labelH8_3.raise_()
        self.labelH4_3.raise_()
        self.hararetProgress_3.raise_()
        self.hararetFrameOn_3.raise_()
        self.kapak2_3.raise_()
        self.yakitFrame_3 = QFrame(self.anaFrameGosterge)
        self.yakitFrame_3.setObjectName(u"yakitFrame_3")
        self.yakitFrame_3.setGeometry(QRect(612, 620, 270, 270))
        self.yakitFrame_3.setStyleSheet(u"background-color:none;")
        self.yakitFrame_3.setFrameShape(QFrame.NoFrame)
        self.yakitFrame_3.setFrameShadow(QFrame.Raised)
        self.yakitGradient_3 = QFrame(self.yakitFrame_3)
        self.yakitGradient_3.setObjectName(u"yakitGradient_3")
        self.yakitGradient_3.setGeometry(QRect(10, 20, 240, 240))
        self.yakitGradient_3.setStyleSheet(u"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.946, y2:0.720818, stop:0 rgba(85, 255, 255, 255), stop:1 rgba(0, 85, 255, 255));\n"
"border-radius: 120px;")
        self.yakitGradient_3.setFrameShape(QFrame.NoFrame)
        self.yakitGradient_3.setFrameShadow(QFrame.Raised)
        self.kapak3_3 = QFrame(self.yakitFrame_3)
        self.kapak3_3.setObjectName(u"kapak3_3")
        self.kapak3_3.setGeometry(QRect(0, 130, 260, 130))
        self.kapak3_3.setStyleSheet(u"background-color: rgb(6, 6, 58);")
        self.kapak3_3.setFrameShape(QFrame.NoFrame)
        self.kapak3_3.setFrameShadow(QFrame.Raised)
        self.yakitFrameIc_3 = QFrame(self.yakitFrame_3)
        self.yakitFrameIc_3.setObjectName(u"yakitFrameIc_3")
        self.yakitFrameIc_3.setGeometry(QRect(20, 30, 220, 220))
        self.yakitFrameIc_3.setStyleSheet(u"background-color: rgb(6, 6, 58);\n"
"border-radius: 110px;")
        self.yakitFrameIc_3.setFrameShape(QFrame.NoFrame)
        self.yakitFrameIc_3.setFrameShadow(QFrame.Raised)
        self.yakitFrameOn_3 = QFrame(self.yakitFrame_3)
        self.yakitFrameOn_3.setObjectName(u"yakitFrameOn_3")
        self.yakitFrameOn_3.setGeometry(QRect(60, 70, 140, 140))
        self.yakitFrameOn_3.setStyleSheet(u"background-color: rgb(3, 2, 34);\n"
"border-radius:70px;")
        self.yakitFrameOn_3.setFrameShape(QFrame.NoFrame)
        self.yakitFrameOn_3.setFrameShadow(QFrame.Raised)
        self.yakit_3 = QLabel(self.yakitFrameOn_3)
        self.yakit_3.setObjectName(u"yakit_3")
        self.yakit_3.setGeometry(QRect(70, 40, 71, 21))
        self.yakit_3.setStyleSheet(u"color: #ffffff; background-color: none")
        self.yakit_3.setAlignment(Qt.AlignCenter)
        self.yakitIcon_3 = QLabel(self.yakitFrameOn_3)
        self.yakitIcon_3.setObjectName(u"yakitIcon_3")
        self.yakitIcon_3.setGeometry(QRect(15, 25, 45, 35))
        self.yakitIcon_3.setStyleSheet(u"background-color: none;")
        self.yakitIcon_3.setPixmap(QPixmap(u"tba3.png"))
        self.yakitIcon_3.setScaledContents(True)
        self.yakitProgress_3 = QFrame(self.yakitFrame_3)
        self.yakitProgress_3.setObjectName(u"yakitProgress_3")
        self.yakitProgress_3.setGeometry(QRect(30, 40, 200, 200))
        self.yakitProgress_3.setStyleSheet(u"background-color: qconicalgradient(cx:0.5, cy:0.5, angle:180, stop:0.011158 rgba(85, 170, 255, 0), stop:0.013089 rgba(249, 201, 111, 255));\n"
"background-color: qconicalgradient(cx:0.5, cy:0.5, angle:180, stop:0.799308 rgba(85, 170, 255, 0), stop:0.803089 rgba(85, 170, 255, 255));\n"
"border-radius: 100px;")
        self.yakitProgress_3.setFrameShape(QFrame.NoFrame)
        self.yakitProgress_3.setFrameShadow(QFrame.Raised)
        self.yakitGolge_3 = QFrame(self.yakitProgress_3)
        self.yakitGolge_3.setObjectName(u"yakitGolge_3")
        self.yakitGolge_3.setGeometry(QRect(10, 10, 180, 180))
        self.yakitGolge_3.setStyleSheet(u"border-radius: 90px;\n"
"background-color: rgba(0, 0, 0,150);\n"
"border-width: 2px;\n"
"border-style: solid;")
        self.yakitGolge_3.setFrameShape(QFrame.NoFrame)
        self.yakitGolge_3.setFrameShadow(QFrame.Raised)
        self.labelYT4_3 = QLabel(self.yakitFrame_3)
        self.labelYT4_3.setObjectName(u"labelYT4_3")
        self.labelYT4_3.setGeometry(QRect(118, 0, 20, 20))
        self.labelYT4_3.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: none;")
        self.labelYT4_3.setAlignment(Qt.AlignCenter)
        self.labelYT2_3 = QLabel(self.yakitFrame_3)
        self.labelYT2_3.setObjectName(u"labelYT2_3")
        self.labelYT2_3.setGeometry(QRect(33, 21, 20, 20))
        self.labelYT2_3.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: none;")
        self.labelYT2_3.setAlignment(Qt.AlignCenter)
        self.labelYT6_3 = QLabel(self.yakitFrame_3)
        self.labelYT6_3.setObjectName(u"labelYT6_3")
        self.labelYT6_3.setGeometry(QRect(203, 21, 20, 20))
        self.labelYT6_3.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: none;")
        self.labelYT6_3.setAlignment(Qt.AlignCenter)
        self.labelYT0_3 = QLabel(self.yakitFrame_3)
        self.labelYT0_3.setObjectName(u"labelYT0_3")
        self.labelYT0_3.setGeometry(QRect(0, 81, 20, 20))
        self.labelYT0_3.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: none;")
        self.labelYT0_3.setAlignment(Qt.AlignCenter)
        self.labelYT8_3 = QLabel(self.yakitFrame_3)
        self.labelYT8_3.setObjectName(u"labelYT8_3")
        self.labelYT8_3.setGeometry(QRect(243, 81, 20, 20))
        self.labelYT8_3.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: none;")
        self.labelYT8_3.setAlignment(Qt.AlignCenter)
        self.yakitGradient_3.raise_()
        self.yakitFrameIc_3.raise_()
        self.yakitProgress_3.raise_()
        self.labelYT4_3.raise_()
        self.labelYT2_3.raise_()
        self.labelYT6_3.raise_()
        self.labelYT0_3.raise_()
        self.labelYT8_3.raise_()
        self.yakitFrameOn_3.raise_()
        self.kapak3_3.raise_()
        self.akuFrame_3 = QFrame(self.anaFrameGosterge)
        self.akuFrame_3.setObjectName(u"akuFrame_3")
        self.akuFrame_3.setGeometry(QRect(899, 620, 270, 270))
        self.akuFrame_3.setStyleSheet(u"background-color:none;")
        self.akuFrame_3.setFrameShape(QFrame.NoFrame)
        self.akuFrame_3.setFrameShadow(QFrame.Raised)
        self.akuGradient_3 = QFrame(self.akuFrame_3)
        self.akuGradient_3.setObjectName(u"akuGradient_3")
        self.akuGradient_3.setGeometry(QRect(10, 20, 240, 240))
        self.akuGradient_3.setStyleSheet(u"border-radius: 120px;\n"
"background-color: qlineargradient(spread:pad, x1:0.999873, y1:0.239, x2:0, y2:0.086, stop:0 rgba(104, 1, 174, 255), stop:1 rgba(200, 107, 92, 255));\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.946, y2:0.720818, stop:0 rgba(85, 255, 255, 255), stop:1 rgba(0, 85, 255, 255));")
        self.akuGradient_3.setFrameShape(QFrame.NoFrame)
        self.akuGradient_3.setFrameShadow(QFrame.Raised)
        self.kapak4_3 = QFrame(self.akuFrame_3)
        self.kapak4_3.setObjectName(u"kapak4_3")
        self.kapak4_3.setGeometry(QRect(0, 130, 260, 130))
        self.kapak4_3.setStyleSheet(u"background-color: rgb(6, 6, 58);")
        self.kapak4_3.setFrameShape(QFrame.NoFrame)
        self.kapak4_3.setFrameShadow(QFrame.Raised)
        self.akuFrameIc_3 = QFrame(self.akuFrame_3)
        self.akuFrameIc_3.setObjectName(u"akuFrameIc_3")
        self.akuFrameIc_3.setGeometry(QRect(20, 30, 220, 220))
        self.akuFrameIc_3.setStyleSheet(u"background-color: rgb(6, 6, 58);\n"
"border-radius: 110px;")
        self.akuFrameIc_3.setFrameShape(QFrame.NoFrame)
        self.akuFrameIc_3.setFrameShadow(QFrame.Raised)
        self.akuFrameOn_3 = QFrame(self.akuFrame_3)
        self.akuFrameOn_3.setObjectName(u"akuFrameOn_3")
        self.akuFrameOn_3.setGeometry(QRect(60, 70, 140, 140))
        self.akuFrameOn_3.setStyleSheet(u"background-color: rgb(3, 2, 34);\n"
"border-radius:70px;")
        self.akuFrameOn_3.setFrameShape(QFrame.NoFrame)
        self.akuFrameOn_3.setFrameShadow(QFrame.Raised)
        self.aku_3 = QLabel(self.akuFrameOn_3)
        self.aku_3.setObjectName(u"aku_3")
        self.aku_3.setGeometry(QRect(70, 40, 71, 21))
        self.aku_3.setStyleSheet(u"color: #ffffff; background-color: none")
        self.aku_3.setAlignment(Qt.AlignCenter)
        self.akuIcon_3 = QLabel(self.akuFrameOn_3)
        self.akuIcon_3.setObjectName(u"akuIcon_3")
        self.akuIcon_3.setGeometry(QRect(15, 25, 40, 35))
        self.akuIcon_3.setStyleSheet(u"background-color: none;")
        self.akuIcon_3.setPixmap(QPixmap(u"tba1.png"))
        self.akuIcon_3.setScaledContents(True)
        self.akuProgress_3 = QFrame(self.akuFrame_3)
        self.akuProgress_3.setObjectName(u"akuProgress_3")
        self.akuProgress_3.setGeometry(QRect(30, 40, 200, 200))
        self.akuProgress_3.setStyleSheet(u"background-color: qconicalgradient(cx:0.5, cy:0.5, angle:180, stop:0.011158 rgba(85, 170, 255, 0), stop:0.013089 rgba(249, 201, 111, 255));\n"
"background-color: qconicalgradient(cx:0.5, cy:0.5, angle:180, stop:0.799308 rgba(85, 170, 255, 0), stop:0.803089 rgba(85, 170, 255, 255));\n"
"border-radius: 100px;")
        self.akuProgress_3.setFrameShape(QFrame.NoFrame)
        self.akuProgress_3.setFrameShadow(QFrame.Raised)
        self.akuGolge_3 = QFrame(self.akuProgress_3)
        self.akuGolge_3.setObjectName(u"akuGolge_3")
        self.akuGolge_3.setGeometry(QRect(10, 10, 180, 180))
        self.akuGolge_3.setStyleSheet(u"border-radius: 90px;\n"
"background-color: rgba(0, 0, 0,150);\n"
"border-width: 2px;\n"
"border-style: solid;")
        self.akuGolge_3.setFrameShape(QFrame.NoFrame)
        self.akuGolge_3.setFrameShadow(QFrame.Raised)
        self.labelA4_3 = QLabel(self.akuFrame_3)
        self.labelA4_3.setObjectName(u"labelA4_3")
        self.labelA4_3.setGeometry(QRect(118, 0, 20, 20))
        self.labelA4_3.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: none;")
        self.labelA4_3.setAlignment(Qt.AlignCenter)
        self.labelA2_3 = QLabel(self.akuFrame_3)
        self.labelA2_3.setObjectName(u"labelA2_3")
        self.labelA2_3.setGeometry(QRect(33, 21, 20, 20))
        self.labelA2_3.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: none;")
        self.labelA2_3.setAlignment(Qt.AlignCenter)
        self.labelA6_3 = QLabel(self.akuFrame_3)
        self.labelA6_3.setObjectName(u"labelA6_3")
        self.labelA6_3.setGeometry(QRect(203, 21, 20, 20))
        self.labelA6_3.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: none;")
        self.labelA6_3.setAlignment(Qt.AlignCenter)
        self.labelA0_3 = QLabel(self.akuFrame_3)
        self.labelA0_3.setObjectName(u"labelA0_3")
        self.labelA0_3.setGeometry(QRect(0, 81, 20, 20))
        self.labelA0_3.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: none;")
        self.labelA0_3.setAlignment(Qt.AlignCenter)
        self.labelA8_3 = QLabel(self.akuFrame_3)
        self.labelA8_3.setObjectName(u"labelA8_3")
        self.labelA8_3.setGeometry(QRect(243, 81, 20, 20))
        self.labelA8_3.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: none;")
        self.labelA8_3.setAlignment(Qt.AlignCenter)
        self.akuGradient_3.raise_()
        self.akuFrameIc_3.raise_()
        self.labelA4_3.raise_()
        self.labelA2_3.raise_()
        self.labelA6_3.raise_()
        self.labelA0_3.raise_()
        self.labelA8_3.raise_()
        self.akuProgress_3.raise_()
        self.akuFrameOn_3.raise_()
        self.kapak4_3.raise_()
        self.resimAku_3 = QLabel(self.anaFrameGosterge)
        self.resimAku_3.setObjectName(u"resimAku_3")
        self.resimAku_3.setGeometry(QRect(190, 30, 80, 60))
        self.resimAku_3.setPixmap(QPixmap(u"aku-icon.png"))
        self.resimAku_3.setScaledContents(True)
        self.resimYag_3 = QLabel(self.anaFrameGosterge)
        self.resimYag_3.setObjectName(u"resimYag_3")
        self.resimYag_3.setGeometry(QRect(280, 30, 80, 60))
        self.resimYag_3.setPixmap(QPixmap(u"ya\u011ficon kopya.png"))
        self.resimYag_3.setScaledContents(True)
        self.resimFren_3 = QLabel(self.anaFrameGosterge)
        self.resimFren_3.setObjectName(u"resimFren_3")
        self.resimFren_3.setGeometry(QRect(380, 30, 80, 60))
        self.resimFren_3.setPixmap(QPixmap(u"BBB1.png"))
        self.resimFren_3.setScaledContents(True)
        self.resimEmniyet_3 = QLabel(self.anaFrameGosterge)
        self.resimEmniyet_3.setObjectName(u"resimEmniyet_3")
        self.resimEmniyet_3.setGeometry(QRect(780, 30, 85, 55))
        self.resimEmniyet_3.setPixmap(QPixmap(u"AAAA kopya.png"))
        self.resimEmniyet_3.setScaledContents(True)
        self.resimHararet_3 = QLabel(self.anaFrameGosterge)
        self.resimHararet_3.setObjectName(u"resimHararet_3")
        self.resimHararet_3.setGeometry(QRect(860, 30, 80, 60))
        self.resimHararet_3.setPixmap(QPixmap(u"hararet3.png"))
        self.resimHararet_3.setScaledContents(True)
        self.resimYakit_3 = QLabel(self.anaFrameGosterge)
        self.resimYakit_3.setObjectName(u"resimYakit_3")
        self.resimYakit_3.setGeometry(QRect(930, 30, 80, 60))
        self.resimYakit_3.setPixmap(QPixmap(u"benzinson2 kopya.png"))
        self.resimYakit_3.setScaledContents(True)
        self.resimSol_3 = QLabel(self.anaFrameGosterge)
        self.resimSol_3.setObjectName(u"resimSol_3")
        self.resimSol_3.setGeometry(QRect(510, 70, 90, 70))
        self.resimSol_3.setPixmap(QPixmap(u"solok3.png"))
        self.resimSol_3.setScaledContents(True)
        self.resimSag_3 = QLabel(self.anaFrameGosterge)
        self.resimSag_3.setObjectName(u"resimSag_3")
        self.resimSag_3.setGeometry(QRect(630, 70, 90, 70))
        self.resimSag_3.setPixmap(QPixmap(u"sagok3.png"))
        self.resimSag_3.setScaledContents(True)
        self.verticalSlider_5 = QSlider(self.anaFrameGosterge)
        self.verticalSlider_5.setObjectName(u"verticalSlider_5")
        self.verticalSlider_5.setGeometry(QRect(30, 260, 21, 161))
        self.verticalSlider_5.setMaximum(85)
        self.verticalSlider_5.setOrientation(Qt.Vertical)
        self.verticalSlider_6 = QSlider(self.anaFrameGosterge)
        self.verticalSlider_6.setObjectName(u"verticalSlider_6")
        self.verticalSlider_6.setGeometry(QRect(1150, 270, 21, 161))
        self.verticalSlider_6.setMaximum(85)
        self.verticalSlider_6.setOrientation(Qt.Vertical)
        self.rpmFrame_3 = QFrame(self.anaFrameGosterge)
        self.rpmFrame_3.setObjectName(u"rpmFrame_3")
        self.rpmFrame_3.setGeometry(QRect(100, 110, 500, 500))
        self.rpmFrame_3.setStyleSheet(u"background-color: none;")
        self.rpmFrame_3.setFrameShape(QFrame.NoFrame)
        self.rpmFrame_3.setFrameShadow(QFrame.Raised)
        self.label10_3 = QLabel(self.rpmFrame_3)
        self.label10_3.setObjectName(u"label10_3")
        self.label10_3.setGeometry(QRect(10, 230, 32, 40))
        self.label10_3.setMaximumSize(QSize(47, 16777215))
        font = QFont()
        font.setPointSize(15)
        self.label10_3.setFont(font)
        self.label10_3.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: none;")
        self.label10_3.setAlignment(Qt.AlignCenter)
        self.label30_3 = QLabel(self.rpmFrame_3)
        self.label30_3.setObjectName(u"label30_3")
        self.label30_3.setGeometry(QRect(460, 230, 30, 40))
        self.label30_3.setMaximumSize(QSize(47, 16777215))
        self.label30_3.setFont(font)
        self.label30_3.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: none;")
        self.label30_3.setAlignment(Qt.AlignCenter)
        self.label20_3 = QLabel(self.rpmFrame_3)
        self.label20_3.setObjectName(u"label20_3")
        self.label20_3.setGeometry(QRect(235, 10, 30, 40))
        self.label20_3.setMaximumSize(QSize(47, 16777215))
        self.label20_3.setFont(font)
        self.label20_3.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: none;")
        self.label20_3.setAlignment(Qt.AlignCenter)
        self.rpmGradient_3 = QFrame(self.rpmFrame_3)
        self.rpmGradient_3.setObjectName(u"rpmGradient_3")
        self.rpmGradient_3.setGeometry(QRect(50, 50, 400, 400))
        self.rpmGradient_3.setStyleSheet(u"border-radius: 200px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0.977273, stop:0.191111 rgba(107, 180, 212, 255), stop:0.762222 rgba(86, 55, 135, 255));")
        self.rpmGradient_3.setFrameShape(QFrame.NoFrame)
        self.rpmGradient_3.setFrameShadow(QFrame.Raised)
        self.label0_3 = QLabel(self.rpmFrame_3)
        self.label0_3.setObjectName(u"label0_3")
        self.label0_3.setGeometry(QRect(133, 425, 30, 40))
        self.label0_3.setMaximumSize(QSize(47, 16777215))
        font1 = QFont()
        font1.setPointSize(15)
        font1.setBold(True)
        self.label0_3.setFont(font1)
        self.label0_3.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color:#00000000;")
        self.label0_3.setAlignment(Qt.AlignCenter)
        self.label5_3 = QLabel(self.rpmFrame_3)
        self.label5_3.setObjectName(u"label5_3")
        self.label5_3.setGeometry(QRect(50, 360, 30, 40))
        self.label5_3.setMaximumSize(QSize(47, 16777215))
        font2 = QFont()
        font2.setPointSize(12)
        self.label5_3.setFont(font2)
        self.label5_3.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color:#00000000;")
        self.label5_3.setAlignment(Qt.AlignCenter)
        self.label40_3 = QLabel(self.rpmFrame_3)
        self.label40_3.setObjectName(u"label40_3")
        self.label40_3.setGeometry(QRect(333, 425, 30, 40))
        self.label40_3.setMaximumSize(QSize(47, 16777215))
        self.label40_3.setFont(font)
        self.label40_3.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color:#00000000;")
        self.label40_3.setAlignment(Qt.AlignCenter)
        self.label35_3 = QLabel(self.rpmFrame_3)
        self.label35_3.setObjectName(u"label35_3")
        self.label35_3.setGeometry(QRect(415, 360, 30, 40))
        self.label35_3.setMaximumSize(QSize(47, 16777215))
        self.label35_3.setFont(font2)
        self.label35_3.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color:#00000000;")
        self.label35_3.setAlignment(Qt.AlignCenter)
        self.rpmFrame1_3 = QFrame(self.rpmFrame_3)
        self.rpmFrame1_3.setObjectName(u"rpmFrame1_3")
        self.rpmFrame1_3.setGeometry(QRect(60, 60, 380, 380))
        self.rpmFrame1_3.setStyleSheet(u"background-color: rgb(3, 2, 34);\n"
"border-radius: 190px;")
        self.rpmFrame1_3.setFrameShape(QFrame.NoFrame)
        self.rpmFrame1_3.setFrameShadow(QFrame.Raised)
        self.rpmFrame2_3 = QFrame(self.rpmFrame_3)
        self.rpmFrame2_3.setObjectName(u"rpmFrame2_3")
        self.rpmFrame2_3.setGeometry(QRect(80, 80, 340, 340))
        self.rpmFrame2_3.setStyleSheet(u"background-color: rgb(7, 7, 61);\n"
"border-radius: 170px;")
        self.rpmFrame2_3.setFrameShape(QFrame.NoFrame)
        self.rpmFrame2_3.setFrameShadow(QFrame.Raised)
        self.rpmFrame3_3 = QFrame(self.rpmFrame_3)
        self.rpmFrame3_3.setObjectName(u"rpmFrame3_3")
        self.rpmFrame3_3.setGeometry(QRect(110, 110, 280, 280))
        self.rpmFrame3_3.setStyleSheet(u"\n"
"border-radius: 140px;\n"
"background-color: rgb(255, 255, 255);\n"
"background-color: rgb(3, 2, 34);")
        self.rpmFrame3_3.setFrameShape(QFrame.NoFrame)
        self.rpmFrame3_3.setFrameShadow(QFrame.Raised)
        self.rpmFrame4_3 = QFrame(self.rpmFrame_3)
        self.rpmFrame4_3.setObjectName(u"rpmFrame4_3")
        self.rpmFrame4_3.setGeometry(QRect(150, 150, 200, 200))
        self.rpmFrame4_3.setStyleSheet(u"background-color: rgb(6, 6, 58);\n"
"border-radius:100px;")
        self.rpmFrame4_3.setFrameShape(QFrame.NoFrame)
        self.rpmFrame4_3.setFrameShadow(QFrame.Raised)
        self.rpm_3 = QLabel(self.rpmFrame4_3)
        self.rpm_3.setObjectName(u"rpm_3")
        self.rpm_3.setGeometry(QRect(50, 30, 91, 71))
        font3 = QFont()
        font3.setPointSize(20)
        self.rpm_3.setFont(font3)
        self.rpm_3.setStyleSheet(u"color: #ffffff")
        self.rpm_3.setAlignment(Qt.AlignCenter)
        self.sabitRpm_3 = QLabel(self.rpmFrame4_3)
        self.sabitRpm_3.setObjectName(u"sabitRpm_3")
        self.sabitRpm_3.setGeometry(QRect(50, 100, 91, 71))
        self.sabitRpm_3.setFont(font3)
        self.sabitRpm_3.setStyleSheet(u"color: #ffffff")
        self.sabitRpm_3.setAlignment(Qt.AlignCenter)
        self.rpmProgress_3 = QFrame(self.rpmFrame_3)
        self.rpmProgress_3.setObjectName(u"rpmProgress_3")
        self.rpmProgress_3.setGeometry(QRect(110, 110, 280, 280))
        self.rpmProgress_3.setStyleSheet(u"background-color: qconicalgradient(cx:0.5, cy:0.5, angle:242.2, stop:0.998 rgba(0, 0, 0, 0), stop:0.9999 rgba(64, 249, 243, 255));\n"
"border-radius: 140px;\n"
"\n"
"")
        self.rpmProgress_3.setFrameShape(QFrame.NoFrame)
        self.rpmProgress_3.setFrameShadow(QFrame.Raised)
        self.rpmGolge_3 = QFrame(self.rpmProgress_3)
        self.rpmGolge_3.setObjectName(u"rpmGolge_3")
        self.rpmGolge_3.setGeometry(QRect(10, 10, 260, 260))
        self.rpmGolge_3.setStyleSheet(u"border-radius: 130px;\n"
"background-color: rgba(0, 0, 0,150);\n"
"border-width: 2px;\n"
"border-style: solid;")
        self.rpmGolge_3.setFrameShape(QFrame.NoFrame)
        self.rpmGolge_3.setFrameShadow(QFrame.Raised)
        self.label15_3 = QLabel(self.rpmFrame_3)
        self.label15_3.setObjectName(u"label15_3")
        self.label15_3.setGeometry(QRect(75, 75, 30, 40))
        self.label15_3.setMaximumSize(QSize(47, 16777215))
        self.label15_3.setFont(font)
        self.label15_3.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: none;")
        self.label15_3.setAlignment(Qt.AlignCenter)
        self.label25_3 = QLabel(self.rpmFrame_3)
        self.label25_3.setObjectName(u"label25_3")
        self.label25_3.setGeometry(QRect(400, 75, 30, 40))
        self.label25_3.setMaximumSize(QSize(47, 16777215))
        self.label25_3.setFont(font)
        self.label25_3.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: none;")
        self.label25_3.setAlignment(Qt.AlignCenter)
        self.label10_3.raise_()
        self.label30_3.raise_()
        self.label20_3.raise_()
        self.rpmGradient_3.raise_()
        self.label0_3.raise_()
        self.label5_3.raise_()
        self.label40_3.raise_()
        self.label35_3.raise_()
        self.rpmFrame1_3.raise_()
        self.rpmFrame2_3.raise_()
        self.rpmFrame3_3.raise_()
        self.label15_3.raise_()
        self.label25_3.raise_()
        self.rpmProgress_3.raise_()
        self.rpmFrame4_3.raise_()
        self.hizFrame_3 = QFrame(self.anaFrameGosterge)
        self.hizFrame_3.setObjectName(u"hizFrame_3")
        self.hizFrame_3.setGeometry(QRect(600, 110, 500, 500))
        font4 = QFont()
        font4.setBold(True)
        self.hizFrame_3.setFont(font4)
        self.hizFrame_3.setStyleSheet(u"background-color: none;")
        self.hizFrame_3.setFrameShape(QFrame.NoFrame)
        self.hizFrame_3.setFrameShadow(QFrame.Raised)
        self.labelYuz_3 = QLabel(self.hizFrame_3)
        self.labelYuz_3.setObjectName(u"labelYuz_3")
        self.labelYuz_3.setGeometry(QRect(455, 260, 40, 40))
        self.labelYuz_3.setMaximumSize(QSize(47, 16777215))
        self.labelYuz_3.setFont(font)
        self.labelYuz_3.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: none;")
        self.labelYuz_3.setAlignment(Qt.AlignCenter)
        self.labelAltmis_3 = QLabel(self.hizFrame_3)
        self.labelAltmis_3.setObjectName(u"labelAltmis_3")
        self.labelAltmis_3.setGeometry(QRect(235, 10, 40, 40))
        self.labelAltmis_3.setMaximumSize(QSize(47, 16777215))
        self.labelAltmis_3.setFont(font)
        self.labelAltmis_3.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: none;")
        self.labelAltmis_3.setAlignment(Qt.AlignCenter)
        self.hizGradient_3 = QFrame(self.hizFrame_3)
        self.hizGradient_3.setObjectName(u"hizGradient_3")
        self.hizGradient_3.setGeometry(QRect(50, 50, 400, 400))
        self.hizGradient_3.setStyleSheet(u"border-radius: 200px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0.977273, stop:0.191111 rgba(107, 180, 212, 255), stop:0.762222 rgba(86, 55, 135, 255));")
        self.hizGradient_3.setFrameShape(QFrame.NoFrame)
        self.hizGradient_3.setFrameShadow(QFrame.Raised)
        self.labelSifir_3 = QLabel(self.hizFrame_3)
        self.labelSifir_3.setObjectName(u"labelSifir_3")
        self.labelSifir_3.setGeometry(QRect(133, 425, 30, 40))
        self.labelSifir_3.setMaximumSize(QSize(47, 16777215))
        self.labelSifir_3.setFont(font)
        self.labelSifir_3.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color:#00000000;")
        self.labelSifir_3.setAlignment(Qt.AlignCenter)
        self.labelYirmi_3 = QLabel(self.hizFrame_3)
        self.labelYirmi_3.setObjectName(u"labelYirmi_3")
        self.labelYirmi_3.setGeometry(QRect(15, 280, 40, 40))
        self.labelYirmi_3.setMaximumSize(QSize(47, 16777215))
        self.labelYirmi_3.setFont(font2)
        self.labelYirmi_3.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color:#00000000;")
        self.labelYirmi_3.setAlignment(Qt.AlignCenter)
        self.labelYuzyirmi_3 = QLabel(self.hizFrame_3)
        self.labelYuzyirmi_3.setObjectName(u"labelYuzyirmi_3")
        self.labelYuzyirmi_3.setGeometry(QRect(333, 425, 40, 40))
        self.labelYuzyirmi_3.setMaximumSize(QSize(47, 16777215))
        self.labelYuzyirmi_3.setFont(font4)
        self.labelYuzyirmi_3.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color:#00000000;")
        self.labelYuzyirmi_3.setAlignment(Qt.AlignCenter)
        self.hizFrame1_3 = QFrame(self.hizFrame_3)
        self.hizFrame1_3.setObjectName(u"hizFrame1_3")
        self.hizFrame1_3.setGeometry(QRect(60, 60, 380, 380))
        self.hizFrame1_3.setStyleSheet(u"background-color: rgb(3, 2, 34);\n"
"border-radius: 190px;")
        self.hizFrame1_3.setFrameShape(QFrame.NoFrame)
        self.hizFrame1_3.setFrameShadow(QFrame.Raised)
        self.hizFrame2_3 = QFrame(self.hizFrame_3)
        self.hizFrame2_3.setObjectName(u"hizFrame2_3")
        self.hizFrame2_3.setGeometry(QRect(80, 80, 340, 340))
        self.hizFrame2_3.setStyleSheet(u"background-color: rgb(7, 7, 61);\n"
"border-radius: 170px;")
        self.hizFrame2_3.setFrameShape(QFrame.NoFrame)
        self.hizFrame2_3.setFrameShadow(QFrame.Raised)
        self.hizFrame3_3 = QFrame(self.hizFrame_3)
        self.hizFrame3_3.setObjectName(u"hizFrame3_3")
        self.hizFrame3_3.setGeometry(QRect(110, 110, 280, 280))
        self.hizFrame3_3.setStyleSheet(u"\n"
"border-radius: 140px;\n"
"background-color: rgb(255, 255, 255);\n"
"background-color: rgb(3, 2, 34);")
        self.hizFrame3_3.setFrameShape(QFrame.NoFrame)
        self.hizFrame3_3.setFrameShadow(QFrame.Raised)
        self.hizFrame4_3 = QFrame(self.hizFrame_3)
        self.hizFrame4_3.setObjectName(u"hizFrame4_3")
        self.hizFrame4_3.setGeometry(QRect(150, 150, 200, 200))
        self.hizFrame4_3.setStyleSheet(u"background-color: rgb(6, 6, 58);\n"
"border-radius:100px;")
        self.hizFrame4_3.setFrameShape(QFrame.NoFrame)
        self.hizFrame4_3.setFrameShadow(QFrame.Raised)
        self.kmh_3 = QLabel(self.hizFrame4_3)
        self.kmh_3.setObjectName(u"kmh_3")
        self.kmh_3.setGeometry(QRect(50, 30, 91, 71))
        self.kmh_3.setFont(font3)
        self.kmh_3.setStyleSheet(u"color: #ffffff")
        self.kmh_3.setAlignment(Qt.AlignCenter)
        self.sabitKmh_3 = QLabel(self.hizFrame4_3)
        self.sabitKmh_3.setObjectName(u"sabitKmh_3")
        self.sabitKmh_3.setGeometry(QRect(50, 100, 91, 71))
        self.sabitKmh_3.setFont(font3)
        self.sabitKmh_3.setStyleSheet(u"color: #ffffff")
        self.sabitKmh_3.setAlignment(Qt.AlignCenter)
        self.hizProgress_3 = QFrame(self.hizFrame_3)
        self.hizProgress_3.setObjectName(u"hizProgress_3")
        self.hizProgress_3.setGeometry(QRect(110, 110, 280, 280))
        self.hizProgress_3.setStyleSheet(u"border-radius: 140px;\n"
"background-color: qconicalgradient(cx:0.5, cy:0.5, angle:242.2, stop:0.998 rgba(96, 85, 255, 0), stop:0.999 rgba(85, 255, 255, 255));\n"
"\n"
"")
        self.hizProgress_3.setFrameShape(QFrame.NoFrame)
        self.hizProgress_3.setFrameShadow(QFrame.Raised)
        self.hizGolge_3 = QFrame(self.hizProgress_3)
        self.hizGolge_3.setObjectName(u"hizGolge_3")
        self.hizGolge_3.setGeometry(QRect(10, 10, 260, 260))
        self.hizGolge_3.setStyleSheet(u"background-color: rgba(0, 0, 0,150);\n"
"border-style:solid;\n"
"border-color: rgb(0,0,0);\n"
"border-width: 2px;\n"
"border-radius: 130px;\n"
"")
        self.hizGolge_3.setFrameShape(QFrame.NoFrame)
        self.hizGolge_3.setFrameShadow(QFrame.Raised)
        self.labelKirk_3 = QLabel(self.hizFrame_3)
        self.labelKirk_3.setObjectName(u"labelKirk_3")
        self.labelKirk_3.setGeometry(QRect(55, 95, 40, 40))
        self.labelKirk_3.setMaximumSize(QSize(47, 16777215))
        self.labelKirk_3.setFont(font)
        self.labelKirk_3.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: none;")
        self.labelKirk_3.setAlignment(Qt.AlignCenter)
        self.labelSeksen_3 = QLabel(self.hizFrame_3)
        self.labelSeksen_3.setObjectName(u"labelSeksen_3")
        self.labelSeksen_3.setGeometry(QRect(400, 85, 40, 40))
        self.labelSeksen_3.setMaximumSize(QSize(47, 16777215))
        self.labelSeksen_3.setFont(font)
        self.labelSeksen_3.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: none;")
        self.labelSeksen_3.setAlignment(Qt.AlignCenter)
        self.labelYuz_3.raise_()
        self.labelAltmis_3.raise_()
        self.hizGradient_3.raise_()
        self.labelSifir_3.raise_()
        self.labelYirmi_3.raise_()
        self.labelYuzyirmi_3.raise_()
        self.hizFrame1_3.raise_()
        self.hizFrame2_3.raise_()
        self.hizFrame3_3.raise_()
        self.hizProgress_3.raise_()
        self.labelKirk_3.raise_()
        self.labelSeksen_3.raise_()
        self.hizFrame4_3.raise_()
        self.verticalSliderYarim_3 = QSlider(self.anaFrameGosterge)
        self.verticalSliderYarim_3.setObjectName(u"verticalSliderYarim_3")
        self.verticalSliderYarim_3.setGeometry(QRect(30, 510, 20, 91))
        self.verticalSliderYarim_3.setOrientation(Qt.Vertical)
        self.pushButtonSag = QPushButton(self.anaFrameGosterge)
        self.pushButtonSag.setObjectName(u"pushButtonSag")
        self.pushButtonSag.setGeometry(QRect(1120, 40, 50, 50))
        self.pushButtonSag.setStyleSheet(u"background-color: rgb(85, 170, 255);")
        icon = QIcon(QIcon.fromTheme(u"cross"))
        self.pushButtonSag.setIcon(icon)
        icon1 = QIcon()
        iconThemeName = u"cross"
        if QIcon.hasThemeIcon(iconThemeName):
            icon1 = QIcon.fromTheme(iconThemeName)
        else:
            icon1.addFile(u".", QSize(), QIcon.Normal, QIcon.Off)
        
        self.stackedWidget.addWidget(self.dashboard)
        self.egim_koltuk = QWidget()
        self.egim_koltuk.setObjectName(u"egim_koltuk")
        self.anaFrameKoltukEgim = QFrame(self.egim_koltuk)
        self.anaFrameKoltukEgim.setObjectName(u"anaFrameKoltukEgim")
        self.anaFrameKoltukEgim.setGeometry(QRect(0, 0, 1200, 800))
        self.anaFrameKoltukEgim.setStyleSheet(u"background-color: rgb(6, 6, 58);")
        self.anaFrameKoltukEgim.setFrameShape(QFrame.NoFrame)
        self.anaFrameKoltukEgim.setFrameShadow(QFrame.Raised)
        self.aracAnaFrame = QFrame(self.anaFrameKoltukEgim)
        self.aracAnaFrame.setObjectName(u"aracAnaFrame")
        self.aracAnaFrame.setGeometry(QRect(40, 100, 400, 650))
        self.aracAnaFrame.setFrameShape(QFrame.NoFrame)
        self.aracAnaFrame.setFrameShadow(QFrame.Raised)
        self.koltukDuzen = QFrame(self.aracAnaFrame)
        self.koltukDuzen.setObjectName(u"koltukDuzen")
        self.koltukDuzen.setGeometry(QRect(65, 280, 248, 280))
        self.koltukDuzen.setStyleSheet(u"")
        self.koltukDuzen.setFrameShape(QFrame.NoFrame)
        self.koltukDuzen.setFrameShadow(QFrame.Raised)
        self.onKoltukSol = QLabel(self.koltukDuzen)
        self.onKoltukSol.setObjectName(u"onKoltukSol")
        self.onKoltukSol.setGeometry(QRect(20, 10, 55, 55))
        self.onKoltukSol.setPixmap(QPixmap(u"son_dashboard/yesilkoltuk1.png"))
        self.onKoltukSol.setScaledContents(True)
        self.onKoltukSag = QLabel(self.koltukDuzen)
        self.onKoltukSag.setObjectName(u"onKoltukSag")
        self.onKoltukSag.setGeometry(QRect(175, 10, 55, 55))
        self.onKoltukSag.setPixmap(QPixmap(u"son_dashboard/k\u0131rm\u0131z\u0131koltuk1.png"))
        self.onKoltukSag.setScaledContents(True)
        self.koltuk1 = QLabel(self.koltukDuzen)
        self.koltuk1.setObjectName(u"koltuk1")
        self.koltuk1.setGeometry(QRect(25, 110, 45, 45))
        self.koltuk1.setPixmap(QPixmap(u"son_dashboard/k\u0131rm\u0131z\u0131koltuk1.png"))
        self.koltuk1.setScaledContents(True)
        self.koltuk2 = QLabel(self.koltukDuzen)
        self.koltuk2.setObjectName(u"koltuk2")
        self.koltuk2.setGeometry(QRect(25, 165, 45, 45))
        self.koltuk2.setPixmap(QPixmap(u"son_dashboard/k\u0131rm\u0131z\u0131koltuk1.png"))
        self.koltuk2.setScaledContents(True)
        self.koltuk3 = QLabel(self.koltukDuzen)
        self.koltuk3.setObjectName(u"koltuk3")
        self.koltuk3.setGeometry(QRect(25, 220, 45, 45))
        self.koltuk3.setPixmap(QPixmap(u"son_dashboard/beyaz1.png"))
        self.koltuk3.setScaledContents(True)
        self.koltukKule = QLabel(self.koltukDuzen)
        self.koltukKule.setObjectName(u"koltukKule")
        self.koltukKule.setGeometry(QRect(105, 130, 45, 45))
        self.koltukKule.setPixmap(QPixmap(u"son_dashboard/k\u0131rm\u0131z\u0131koltuk1.png"))
        self.koltukKule.setScaledContents(True)
        self.koltuk4 = QLabel(self.koltukDuzen)
        self.koltuk4.setObjectName(u"koltuk4")
        self.koltuk4.setGeometry(QRect(185, 110, 45, 45))
        self.koltuk4.setPixmap(QPixmap(u"son_dashboard/beyaz1.png"))
        self.koltuk4.setScaledContents(True)
        self.koltuk5 = QLabel(self.koltukDuzen)
        self.koltuk5.setObjectName(u"koltuk5")
        self.koltuk5.setGeometry(QRect(185, 165, 45, 45))
        self.koltuk5.setPixmap(QPixmap(u"son_dashboard/yesilkoltuk1.png"))
        self.koltuk5.setScaledContents(True)
        self.koltuk6 = QLabel(self.koltukDuzen)
        self.koltuk6.setObjectName(u"koltuk6")
        self.koltuk6.setGeometry(QRect(185, 220, 45, 45))
        self.koltuk6.setPixmap(QPixmap(u"son_dashboard/yesilkoltuk1.png"))
        self.koltuk6.setScaledContents(True)
        self.arac = QLabel(self.aracAnaFrame)
        self.arac.setObjectName(u"arac")
        self.arac.setGeometry(QRect(0, 0, 380, 650))
        self.arac.setPixmap(QPixmap(u"son_dashboard/kobraustten.png"))
        self.arac.setScaledContents(True)
        self.arac.raise_()
        self.koltukDuzen.raise_()
        self.egimAnaFrame = QFrame(self.anaFrameKoltukEgim)
        self.egimAnaFrame.setObjectName(u"egimAnaFrame")
        self.egimAnaFrame.setGeometry(QRect(480, 80, 700, 700))
        self.egimAnaFrame.setStyleSheet(u"background-color: rgb(170, 255, 255);\n"
"background-color: rgb(6, 6, 58);")
        self.egimAnaFrame.setFrameShape(QFrame.NoFrame)
        self.egimAnaFrame.setFrameShadow(QFrame.Raised)
        self.egimFrame1 = QFrame(self.egimAnaFrame)
        self.egimFrame1.setObjectName(u"egimFrame1")
        self.egimFrame1.setGeometry(QRect(50, 50, 600, 600))
        self.egimFrame1.setStyleSheet(u"border-radius: 300px;\n"
"background-color: rgb(3, 2, 34);")
        self.egimFrame1.setFrameShape(QFrame.NoFrame)
        self.egimFrame1.setFrameShadow(QFrame.Raised)
        self.labelSolust10 = QLabel(self.egimAnaFrame)
        self.labelSolust10.setObjectName(u"labelSolust10")
        self.labelSolust10.setGeometry(QRect(20, 210, 40, 40))
        self.labelSolust10.setStyleSheet(u"background-color: transparent;")
        self.labelSolust10.setAlignment(Qt.AlignCenter)
        self.labelSolust20 = QLabel(self.egimAnaFrame)
        self.labelSolust20.setObjectName(u"labelSolust20")
        self.labelSolust20.setGeometry(QRect(80, 100, 40, 40))
        self.labelSolust20.setStyleSheet(u"background-color: transparent;")
        self.labelSolust20.setAlignment(Qt.AlignCenter)
        self.labelSolust30 = QLabel(self.egimAnaFrame)
        self.labelSolust30.setObjectName(u"labelSolust30")
        self.labelSolust30.setGeometry(QRect(160, 40, 40, 40))
        self.labelSolust30.setStyleSheet(u"background-color: transparent;")
        self.labelSolust30.setAlignment(Qt.AlignCenter)
        self.labelSolust40 = QLabel(self.egimAnaFrame)
        self.labelSolust40.setObjectName(u"labelSolust40")
        self.labelSolust40.setGeometry(QRect(275, 0, 40, 40))
        self.labelSolust40.setStyleSheet(u"background-color: transparent;")
        self.labelSolust40.setAlignment(Qt.AlignCenter)
        self.labelSagust10 = QLabel(self.egimAnaFrame)
        self.labelSagust10.setObjectName(u"labelSagust10")
        self.labelSagust10.setGeometry(QRect(640, 210, 40, 40))
        self.labelSagust10.setStyleSheet(u"background-color: transparent;")
        self.labelSagust10.setAlignment(Qt.AlignCenter)
        self.labelSagust20 = QLabel(self.egimAnaFrame)
        self.labelSagust20.setObjectName(u"labelSagust20")
        self.labelSagust20.setGeometry(QRect(580, 100, 40, 40))
        self.labelSagust20.setStyleSheet(u"background-color: transparent;")
        self.labelSagust20.setAlignment(Qt.AlignCenter)
        self.labelSagust30 = QLabel(self.egimAnaFrame)
        self.labelSagust30.setObjectName(u"labelSagust30")
        self.labelSagust30.setGeometry(QRect(500, 40, 40, 40))
        self.labelSagust30.setStyleSheet(u"background-color: transparent;")
        self.labelSagust30.setAlignment(Qt.AlignCenter)
        self.labelSagust40 = QLabel(self.egimAnaFrame)
        self.labelSagust40.setObjectName(u"labelSagust40")
        self.labelSagust40.setGeometry(QRect(385, 0, 40, 40))
        self.labelSagust40.setStyleSheet(u"background-color: transparent;")
        self.labelSagust40.setAlignment(Qt.AlignCenter)
        self.labelSolalt60 = QLabel(self.egimAnaFrame)
        self.labelSolalt60.setObjectName(u"labelSolalt60")
        self.labelSolalt60.setGeometry(QRect(275, 660, 40, 40))
        self.labelSolalt60.setStyleSheet(u"background-color: transparent;")
        self.labelSolalt60.setAlignment(Qt.AlignCenter)
        self.labelSagalt60 = QLabel(self.egimAnaFrame)
        self.labelSagalt60.setObjectName(u"labelSagalt60")
        self.labelSagalt60.setGeometry(QRect(385, 660, 40, 40))
        self.labelSagalt60.setStyleSheet(u"background-color: transparent;")
        self.labelSagalt60.setAlignment(Qt.AlignCenter)
        self.labelSolalt20 = QLabel(self.egimAnaFrame)
        self.labelSolalt20.setObjectName(u"labelSolalt20")
        self.labelSolalt20.setGeometry(QRect(30, 480, 40, 40))
        self.labelSolalt20.setStyleSheet(u"background-color: transparent;")
        self.labelSolalt20.setAlignment(Qt.AlignCenter)
        self.labelSolalt30 = QLabel(self.egimAnaFrame)
        self.labelSolalt30.setObjectName(u"labelSolalt30")
        self.labelSolalt30.setGeometry(QRect(65, 540, 40, 40))
        self.labelSolalt30.setStyleSheet(u"background-color: transparent;")
        self.labelSolalt30.setAlignment(Qt.AlignCenter)
        self.labelSolalt40 = QLabel(self.egimAnaFrame)
        self.labelSolalt40.setObjectName(u"labelSolalt40")
        self.labelSolalt40.setGeometry(QRect(125, 600, 40, 40))
        self.labelSolalt40.setStyleSheet(u"background-color: transparent;")
        self.labelSolalt40.setAlignment(Qt.AlignCenter)
        self.labelSolalt50 = QLabel(self.egimAnaFrame)
        self.labelSolalt50.setObjectName(u"labelSolalt50")
        self.labelSolalt50.setGeometry(QRect(200, 640, 40, 40))
        self.labelSolalt50.setStyleSheet(u"background-color: transparent;")
        self.labelSolalt50.setAlignment(Qt.AlignCenter)
        self.labelSagalt50 = QLabel(self.egimAnaFrame)
        self.labelSagalt50.setObjectName(u"labelSagalt50")
        self.labelSagalt50.setGeometry(QRect(460, 640, 40, 40))
        self.labelSagalt50.setStyleSheet(u"background-color: transparent;")
        self.labelSagalt50.setAlignment(Qt.AlignCenter)
        self.labelSagalt40 = QLabel(self.egimAnaFrame)
        self.labelSagalt40.setObjectName(u"labelSagalt40")
        self.labelSagalt40.setGeometry(QRect(535, 600, 40, 40))
        self.labelSagalt40.setStyleSheet(u"background-color: transparent;")
        self.labelSagalt40.setAlignment(Qt.AlignCenter)
        self.labelSagalt30 = QLabel(self.egimAnaFrame)
        self.labelSagalt30.setObjectName(u"labelSagalt30")
        self.labelSagalt30.setGeometry(QRect(595, 540, 40, 40))
        self.labelSagalt30.setStyleSheet(u"background-color: transparent;")
        self.labelSagalt30.setAlignment(Qt.AlignCenter)
        self.labelSagalt20 = QLabel(self.egimAnaFrame)
        self.labelSagalt20.setObjectName(u"labelSagalt20")
        self.labelSagalt20.setGeometry(QRect(630, 480, 40, 40))
        self.labelSagalt20.setStyleSheet(u"background-color: transparent;")
        self.labelSagalt20.setAlignment(Qt.AlignCenter)
        self.labelSagalt10 = QLabel(self.egimAnaFrame)
        self.labelSagalt10.setObjectName(u"labelSagalt10")
        self.labelSagalt10.setGeometry(QRect(650, 420, 40, 40))
        self.labelSagalt10.setStyleSheet(u"background-color: transparent;")
        self.labelSagalt10.setAlignment(Qt.AlignCenter)
        self.egimGradient = QFrame(self.egimAnaFrame)
        self.egimGradient.setObjectName(u"egimGradient")
        self.egimGradient.setGeometry(QRect(40, 40, 620, 620))
        self.egimGradient.setStyleSheet(u"background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.526, y2:0.988636, stop:0 rgba(254, 124, 0, 255), stop:1 rgba(108, 1, 175, 255));\n"
"border-radius: 310px;")
        self.egimGradient.setFrameShape(QFrame.NoFrame)
        self.egimGradient.setFrameShadow(QFrame.Raised)
        self.yatayCizgi = QFrame(self.egimAnaFrame)
        self.yatayCizgi.setObjectName(u"yatayCizgi")
        self.yatayCizgi.setGeometry(QRect(0, 330, 700, 40))
        self.yatayCizgi.setStyleSheet(u"background-color: rgb(6, 6, 58);")
        self.yatayCizgi.setFrameShape(QFrame.NoFrame)
        self.yatayCizgi.setFrameShadow(QFrame.Raised)
        self.kirmizi = QFrame(self.yatayCizgi)
        self.kirmizi.setObjectName(u"kirmizi")
        self.kirmizi.setGeometry(QRect(65, 15, 555, 10))
        self.kirmizi.setStyleSheet(u"background-color: rgb(255, 0, 0);")
        self.kirmizi.setFrameShape(QFrame.NoFrame)
        self.kirmizi.setFrameShadow(QFrame.Raised)
        self.eksi = QLabel(self.yatayCizgi)
        self.eksi.setObjectName(u"eksi")
        self.eksi.setGeometry(QRect(40, 0, 40, 40))
        self.eksi.setAlignment(Qt.AlignCenter)
        self.arti = QLabel(self.yatayCizgi)
        self.arti.setObjectName(u"arti")
        self.arti.setGeometry(QRect(620, 0, 40, 40))
        self.arti.setAlignment(Qt.AlignCenter)
        self.dikeyCizgi = QFrame(self.egimAnaFrame)
        self.dikeyCizgi.setObjectName(u"dikeyCizgi")
        self.dikeyCizgi.setGeometry(QRect(330, 0, 40, 700))
        self.dikeyCizgi.setStyleSheet(u"background-color: rgb(6, 6, 58);")
        self.dikeyCizgi.setFrameShape(QFrame.NoFrame)
        self.dikeyCizgi.setFrameShadow(QFrame.Raised)
        self.egimFrameOnYuz = QFrame(self.egimAnaFrame)
        self.egimFrameOnYuz.setObjectName(u"egimFrameOnYuz")
        self.egimFrameOnYuz.setGeometry(QRect(100, 100, 500, 500))
        self.egimFrameOnYuz.setStyleSheet(u"border-radius: 250px;\n"
"background-color: rgba(6, 6, 58,255);")
        self.egimFrameOnYuz.setFrameShape(QFrame.NoFrame)
        self.egimFrameOnYuz.setFrameShadow(QFrame.Raised)
        self.dikey_egim_resim = QLabel(self.egimFrameOnYuz)
        self.dikey_egim_resim.setObjectName(u"dikey_egim_resim")
        self.dikey_egim_resim.setGeometry(QRect(110, 260, 270, 150))
        self.dikey_egim_resim.setStyleSheet(u"background-color: none;")
        self.dikey_egim_resim.setPixmap(QPixmap(u"son_dashboard/kobrayan.png"))
        self.dikey_egim_resim.setScaledContents(True)
        self.dikey_egim_resim.setMargin(-1)
        self.dikey_egim_deger = QLabel(self.egimFrameOnYuz)
        self.dikey_egim_deger.setObjectName(u"dikey_egim_deger")
        self.dikey_egim_deger.setGeometry(QRect(250, 420, 120, 40))
        self.dikey_egim_deger.setStyleSheet(u"background-color: none;")
        self.dikey_egim_deger.setAlignment(Qt.AlignCenter)
        self.dikey_egim = QLabel(self.egimFrameOnYuz)
        self.dikey_egim.setObjectName(u"dikey_egim")
        self.dikey_egim.setGeometry(QRect(130, 420, 120, 40))
        self.dikey_egim.setStyleSheet(u"background-color: none;")
        self.dikey_egim.setAlignment(Qt.AlignCenter)
        self.yanal_egim_resim = QLabel(self.egimFrameOnYuz)
        self.yanal_egim_resim.setObjectName(u"yanal_egim_resim")
        self.yanal_egim_resim.setGeometry(QRect(170, 30, 170, 150))
        self.yanal_egim_resim.setStyleSheet(u"background-color: none;")
        self.yanal_egim_resim.setPixmap(QPixmap(u"son_dashboard/kobraon.png"))
        self.yanal_egim_resim.setScaledContents(True)
        self.yanal_egim_resim.setMargin(-1)
        self.dikey_egim_2 = QLabel(self.egimFrameOnYuz)
        self.dikey_egim_2.setObjectName(u"dikey_egim_2")
        self.dikey_egim_2.setGeometry(QRect(130, 190, 120, 40))
        self.dikey_egim_2.setStyleSheet(u"background-color: none;")
        self.dikey_egim_2.setAlignment(Qt.AlignCenter)
        self.dikey_egim_deger_2 = QLabel(self.egimFrameOnYuz)
        self.dikey_egim_deger_2.setObjectName(u"dikey_egim_deger_2")
        self.dikey_egim_deger_2.setGeometry(QRect(250, 190, 120, 40))
        self.dikey_egim_deger_2.setStyleSheet(u"background-color: none;")
        self.dikey_egim_deger_2.setAlignment(Qt.AlignCenter)
        self.solUstProgress = QFrame(self.egimAnaFrame)
        self.solUstProgress.setObjectName(u"solUstProgress")
        self.solUstProgress.setGeometry(QRect(75, 75, 275, 275))
        self.solUstProgress.setStyleSheet(u"QFrame{\n"
"border-top-left-radius: 275px;\n"
"background-color: rgb(255, 255, 127);\n"
"background-color: rgb(252, 201, 109);\n"
"background-color: qconicalgradient(cx:1, cy:1, angle:180, stop:0.858757 rgba(85, 170, 255, 0), stop:0.860056 rgba(252, 201, 109, 255));\n"
"}")
        self.solUstProgress.setFrameShape(QFrame.NoFrame)
        self.solUstProgress.setFrameShadow(QFrame.Raised)
        self.sagUstProgress = QFrame(self.egimAnaFrame)
        self.sagUstProgress.setObjectName(u"sagUstProgress")
        self.sagUstProgress.setGeometry(QRect(350, 75, 275, 275))
        self.sagUstProgress.setStyleSheet(u"QFrame{\n"
"border-top-right-radius: 275px;\n"
"background-color: qconicalgradient(cx:0, cy:1, angle:0, stop:0.138593 rgba(252, 201, 109, 255), stop:0.14 rgba(85, 170, 255, 0));\n"
"	background-color: qconicalgradient(cx:0, cy:1, angle:0, stop:0.184773 rgba(252, 201, 109, 255), stop:0.1875 rgba(85, 170, 255, 0));\n"
"}")
        self.sagUstProgress.setFrameShape(QFrame.NoFrame)
        self.sagUstProgress.setFrameShadow(QFrame.Raised)
        self.solAltProgress = QFrame(self.egimAnaFrame)
        self.solAltProgress.setObjectName(u"solAltProgress")
        self.solAltProgress.setGeometry(QRect(75, 350, 275, 275))
        self.solAltProgress.setStyleSheet(u"border-bottom-left-radius: 275px;\n"
"background-color: rgb(255, 255, 127);\n"
"background-color: rgb(252, 201, 109);\n"
"background-color: qconicalgradient(cx:1, cy:0, angle:180, stop:0.158192 rgba(121, 50, 190, 255), stop:0.163842 rgba(85, 170, 255, 0));\n"
"")
        self.solAltProgress.setFrameShape(QFrame.NoFrame)
        self.solAltProgress.setFrameShadow(QFrame.Raised)
        self.sagAltProgress = QFrame(self.egimAnaFrame)
        self.sagAltProgress.setObjectName(u"sagAltProgress")
        self.sagAltProgress.setGeometry(QRect(350, 350, 275, 275))
        self.sagAltProgress.setStyleSheet(u"border-bottom-right-radius: 275px;\n"
"background-color: rgb(255, 255, 127);\n"
"background-color: rgb(252, 201, 109);\n"
"background-color: qconicalgradient(cx:0, cy:0, angle:0, stop:0.841808 rgba(85, 170, 255, 0), stop:0.853107 rgba(121, 50, 190, 255));")
        self.sagAltProgress.setFrameShape(QFrame.NoFrame)
        self.sagAltProgress.setFrameShadow(QFrame.Raised)
        self.golge = QFrame(self.egimAnaFrame)
        self.golge.setObjectName(u"golge")
        self.golge.setGeometry(QRect(95, 95, 510, 510))
        self.golge.setStyleSheet(u"background-color: rgba(0, 0, 0,150);\n"
"border-radius: 255px;\n"
"border-style: solid;\n"
"border-width: 2px;")
        self.golge.setFrameShape(QFrame.NoFrame)
        self.golge.setFrameShadow(QFrame.Raised)
        self.labelSolalt10 = QLabel(self.egimAnaFrame)
        self.labelSolalt10.setObjectName(u"labelSolalt10")
        self.labelSolalt10.setGeometry(QRect(10, 420, 40, 40))
        self.labelSolalt10.setStyleSheet(u"background-color: transparent;")
        self.labelSolalt10.setAlignment(Qt.AlignCenter)
        self.labelSagalt20.raise_()
        self.labelSagalt30.raise_()
        self.labelSagalt40.raise_()
        self.labelSagalt50.raise_()
        self.labelSagust10.raise_()
        self.labelSagust20.raise_()
        self.labelSagust30.raise_()
        self.labelSolalt20.raise_()
        self.labelSolalt30.raise_()
        self.labelSolalt40.raise_()
        self.labelSolalt50.raise_()
        self.labelSolalt60.raise_()
        self.labelSolust10.raise_()
        self.labelSolust20.raise_()
        self.labelSolust40.raise_()
        self.labelSagalt10.raise_()
        self.labelSagalt60.raise_()
        self.labelSagust40.raise_()
        self.labelSolust30.raise_()
        self.egimGradient.raise_()
        self.egimFrame1.raise_()
        self.sagUstProgress.raise_()
        self.solUstProgress.raise_()
        self.solAltProgress.raise_()
        self.sagAltProgress.raise_()
        self.golge.raise_()
        self.dikeyCizgi.raise_()
        self.egimFrameOnYuz.raise_()
        self.yatayCizgi.raise_()
        self.labelSolalt10.raise_()
        self.emniyet_kemeri = QLabel(self.anaFrameKoltukEgim)
        self.emniyet_kemeri.setObjectName(u"emniyet_kemeri")
        self.emniyet_kemeri.setGeometry(QRect(40, 30, 400, 50))
        self.emniyet_kemeri.setAlignment(Qt.AlignCenter)
        self.egim_kontrol = QLabel(self.anaFrameKoltukEgim)
        self.egim_kontrol.setObjectName(u"egim_kontrol")
        self.egim_kontrol.setGeometry(QRect(480, 30, 700, 50))
        self.egim_kontrol.setAlignment(Qt.AlignCenter)
        self.sliderKume = QFrame(self.anaFrameKoltukEgim)
        self.sliderKume.setObjectName(u"sliderKume")
        self.sliderKume.setGeometry(QRect(0, 100, 51, 671))
        self.sliderKume.setFrameShape(QFrame.NoFrame)
        self.sliderKume.setFrameShadow(QFrame.Raised)
        self.LabelSolUst = QLabel(self.sliderKume)
        self.LabelSolUst.setObjectName(u"LabelSolUst")
        self.LabelSolUst.setGeometry(QRect(10, 10, 30, 30))
        self.LabelSolUst.setAlignment(Qt.AlignCenter)
        self.sliderSolUst = QSlider(self.sliderKume)
        self.sliderSolUst.setObjectName(u"sliderSolUst")
        self.sliderSolUst.setGeometry(QRect(20, 40, 18, 110))
        self.sliderSolUst.setMaximum(24)
        self.sliderSolUst.setOrientation(Qt.Vertical)
        self.labelSagUst = QLabel(self.sliderKume)
        self.labelSagUst.setObjectName(u"labelSagUst")
        self.labelSagUst.setGeometry(QRect(10, 350, 35, 30))
        self.labelSagUst.setAlignment(Qt.AlignCenter)
        self.labelSolAlt = QLabel(self.sliderKume)
        self.labelSolAlt.setObjectName(u"labelSolAlt")
        self.labelSolAlt.setGeometry(QRect(10, 180, 30, 30))
        self.labelSolAlt.setAlignment(Qt.AlignCenter)
        self.sliderSagAlt = QSlider(self.sliderKume)
        self.sliderSagAlt.setObjectName(u"sliderSagAlt")
        self.sliderSagAlt.setGeometry(QRect(20, 550, 18, 110))
        self.sliderSagAlt.setMaximum(24)
        self.sliderSagAlt.setOrientation(Qt.Vertical)
        self.sliderSolAlt = QSlider(self.sliderKume)
        self.sliderSolAlt.setObjectName(u"sliderSolAlt")
        self.sliderSolAlt.setGeometry(QRect(20, 210, 18, 110))
        self.sliderSolAlt.setMaximum(24)
        self.sliderSolAlt.setOrientation(Qt.Vertical)
        self.sliderSagUst = QSlider(self.sliderKume)
        self.sliderSagUst.setObjectName(u"sliderSagUst")
        self.sliderSagUst.setGeometry(QRect(20, 380, 18, 110))
        self.sliderSagUst.setMaximum(24)
        self.sliderSagUst.setOrientation(Qt.Vertical)
        self.labelSagAlt = QLabel(self.sliderKume)
        self.labelSagAlt.setObjectName(u"labelSagAlt")
        self.labelSagAlt.setGeometry(QRect(10, 520, 35, 30))
        self.labelSagAlt.setAlignment(Qt.AlignCenter)
        self.pushButtonGeri = QPushButton(self.anaFrameKoltukEgim)
        self.pushButtonGeri.setObjectName(u"pushButtonGeri")
        self.pushButtonGeri.setGeometry(QRect(1120, 40, 50, 50))
        self.pushButtonGeri.setStyleSheet(u"background-color: rgb(85, 170, 255);")
        self.pushButtonGeri.setIcon(icon1)
        self.stackedWidget.addWidget(self.egim_koltuk)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        self.stackedWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.yag_3.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:11pt;font-family: Arial Black\">OIL/PSI</span></p></body></html>", None))
        self.yagIcon_3.setText("")
        self.labelY0_3.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:11pt; font-family: Arial Black\">0</span></p></body></html>", None))
        self.labelY2_3.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:11pt; font-family: Arial Black\">2</span></p></body></html>", None))
        self.labelY4_3.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:11pt; font-family: Arial Black\">4</span></p></body></html>", None))
        self.labelY6_3.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:11pt; font-family: Arial Black\">6</span></p></body></html>", None))
        self.labelY8_3.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:11pt; font-family: Arial Black\">8</span></p></body></html>", None))
        self.hararet_3.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-family:'Arial Black'; font-size:12pt;\">TEMP</span></p></body></html>", None))
        self.hararetIcon_3.setText("")
        self.labelH6_3.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:11pt; font-family: Arial Black\">6</span></p></body></html>", None))
        self.labelH2_3.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:11pt; font-family: Arial Black\">2</span></p></body></html>", None))
        self.labelH0_3.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:11pt; font-family: Arial Black\">0</span></p></body></html>", None))
        self.labelH8_3.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:11pt; font-family: Arial Black\">8</span></p></body></html>", None))
        self.labelH4_3.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:11pt; font-family: Arial Black\">4</span></p></body></html>", None))
        self.yakit_3.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-family:'Arial Black'; font-size:12pt;\">FUEL</span></p></body></html>", None))
        self.yakitIcon_3.setText("")
        self.labelYT4_3.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:11pt; font-family: Arial Black\">4</span></p></body></html>", None))
        self.labelYT2_3.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:11pt; font-family: Arial Black\">2</span></p></body></html>", None))
        self.labelYT6_3.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:11pt; font-family: Arial Black\">6</span></p></body></html>", None))
        self.labelYT0_3.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:11pt; font-family: Arial Black\">0</span></p></body></html>", None))
        self.labelYT8_3.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:11pt; font-family: Arial Black\">8</span></p></body></html>", None))
        self.aku_3.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-family:'Arial Black'; font-size:12pt;\">VOLTS</span></p></body></html>", None))
        self.akuIcon_3.setText("")
        self.labelA4_3.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:11pt; font-family: Arial Black\">4</span></p></body></html>", None))
        self.labelA2_3.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:11pt; font-family: Arial Black\">2</span></p></body></html>", None))
        self.labelA6_3.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:11pt; font-family: Arial Black\">6</span></p></body></html>", None))
        self.labelA0_3.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:11pt; font-family: Arial Black\">0</span></p></body></html>", None))
        self.labelA8_3.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:11pt; font-family: Arial Black\">8</span></p></body></html>", None))
        self.resimAku_3.setText("")
        self.resimYag_3.setText("")
        self.resimFren_3.setText("")
        self.resimEmniyet_3.setText("")
        self.resimHararet_3.setText("")
        self.resimYakit_3.setText("")
        self.resimSol_3.setText("")
        self.resimSag_3.setText("")
        self.label10_3.setText(QCoreApplication.translate("MainWindow", u"<p><span style=\" font-size:16pt; font-weight:600;font-family:Arial Black\">10</span></p>", None))
        self.label30_3.setText(QCoreApplication.translate("MainWindow", u"<p><span style=\" font-size:16pt; font-weight:600;font-family:Arial Black\">30</span></p>", None))
        self.label20_3.setText(QCoreApplication.translate("MainWindow", u"<p><span style=\" font-size:16pt; font-weight:600;font-family:Arial Black\">20</span></p>", None))
        self.label0_3.setText(QCoreApplication.translate("MainWindow", u"<p><span style=\" font-size:16pt; font-weight:600;font-family:Arial Black\">0</span></p>", None))
        self.label5_3.setText(QCoreApplication.translate("MainWindow", u"<p><span style=\" font-size:14pt; font-weight:600;font-family:Arial Black\">5</span></p>", None))
        self.label40_3.setText(QCoreApplication.translate("MainWindow", u"<p><span style=\" font-size:16pt; font-weight:600;font-family:Arial Black;\">40</span></p>", None))
        self.label35_3.setText(QCoreApplication.translate("MainWindow", u"<p><span style=\" font-size:14pt; font-weight:600;font-family:Arial Black;\">35</span></p>", None))
        self.rpm_3.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.sabitRpm_3.setText(QCoreApplication.translate("MainWindow", u"Rpm", None))
        self.label15_3.setText(QCoreApplication.translate("MainWindow", u"<p><span style=\" font-size:14pt; font-weight:600;font-family:Arial Black\">15</span></p>", None))
        self.label25_3.setText(QCoreApplication.translate("MainWindow", u"<p><span style=\" font-size:14pt; font-weight:600;font-family:Arial Black\">25</span></p>", None))
        self.labelYuz_3.setText(QCoreApplication.translate("MainWindow", u"<p><span style=\" font-size:15pt; font-weight:600;font-family:Arial Black\">100</span></p>", None))
        self.labelAltmis_3.setText(QCoreApplication.translate("MainWindow", u"<p><span style=\" font-size:15pt; font-weight:600;font-family:Arial Black\">60</span></p>", None))
        self.labelSifir_3.setText(QCoreApplication.translate("MainWindow", u"<p><span style=\" font-size:15pt; font-weight:600;font-family:Arial Black\">0</span></p>", None))
        self.labelYirmi_3.setText(QCoreApplication.translate("MainWindow", u"<p><span style=\" font-size:15pt; font-weight:600;font-family:Arial Black\">20</span></p>", None))
        self.labelYuzyirmi_3.setText(QCoreApplication.translate("MainWindow", u"<p><span style=\" font-size:15pt; font-weight:600;font-family:Arial Black\">120</span></p>", None))
        self.kmh_3.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.sabitKmh_3.setText(QCoreApplication.translate("MainWindow", u"Km/h", None))
        self.labelKirk_3.setText(QCoreApplication.translate("MainWindow", u"<p><span style=\" font-size:15pt; font-weight:600;font-family:Arial Black\">40</span></p>", None))
        self.labelSeksen_3.setText(QCoreApplication.translate("MainWindow", u"<p><span style=\" font-size:15pt; font-weight:600;font-family:Arial Black\">80</span></p>", None))
        self.pushButtonSag.setText(QCoreApplication.translate("MainWindow", u">>", None))
        self.onKoltukSol.setText("")
        self.onKoltukSag.setText("")
        self.koltuk1.setText("")
        self.koltuk2.setText("")
        self.koltuk3.setText("")
        self.koltukKule.setText("")
        self.koltuk4.setText("")
        self.koltuk5.setText("")
        self.koltuk6.setText("")
        self.arac.setText("")
        self.labelSolust10.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt; font-family: Arial Black;  color: #ffffff\">10</span></p></body></html>", None))
        self.labelSolust20.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt; font-family: Arial Black;  color: #ffffff\">20</span></p></body></html>", None))
        self.labelSolust30.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt; font-family: Arial Black;  color: #ffffff\">30</span></p></body></html>", None))
        self.labelSolust40.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt; font-family: Arial Black;  color: #ff0000\">40</span></p></body></html>", None))
        self.labelSagust10.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt; font-family: Arial Black;  color: #ffffff\">10</span></p></body></html>", None))
        self.labelSagust20.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt; font-family: Arial Black;  color: #ffffff\">20</span></p></body></html>", None))
        self.labelSagust30.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt; font-family: Arial Black;  color: #ffffff\">30</span></p></body></html>", None))
        self.labelSagust40.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt; font-family: Arial Black;  color: #ff0000\">40</span></p></body></html>", None))
        self.labelSolalt60.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt; font-family: Arial Black;  color: #ff0000\">60</span></p></body></html>", None))
        self.labelSagalt60.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt; font-family: Arial Black;  color: #ff0000\">60</span></p></body></html>", None))
        self.labelSolalt20.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt; font-family: Arial Black;  color: #ffffff\">20</span></p></body></html>", None))
        self.labelSolalt30.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt; font-family: Arial Black;  color: #ffffff\">30</span></p></body></html>", None))
        self.labelSolalt40.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt; font-family: Arial Black;  color: #ffffff\">40</span></p></body></html>", None))
        self.labelSolalt50.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt; font-family: Arial Black;  color: #ffffff\">50</span></p></body></html>", None))
        self.labelSagalt50.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt; font-family: Arial Black;  color: #ffffff\">50</span></p></body></html>", None))
        self.labelSagalt40.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt; font-family: Arial Black;  color: #ffffff\">40</span></p></body></html>", None))
        self.labelSagalt30.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt; font-family: Arial Black;  color: #ffffff\">30</span></p></body></html>", None))
        self.labelSagalt20.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt; font-family: Arial Black;  color: #ffffff\">20</span></p></body></html>", None))
        self.labelSagalt10.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt; font-family: Arial Black;  color: #ffffff\">10</span></p></body></html>", None))
        self.eksi.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:22pt; color: #ffffff; font-family: Arial Black\">-</span></p></body></html>", None))
        self.arti.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:22pt; color: #ffffff; font-family: Arial Black\">+</span></p></body></html>", None))
        self.dikey_egim_resim.setText("")
        self.dikey_egim_deger.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:20pt; color: #ffffff; font-family: Arial Black\">10</span></p></body></html>", None))
        self.dikey_egim.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:12pt; color: #ffffff; font-family: Arial Black\">Dikey E\u011fim</span></p></body></html>", None))
        self.yanal_egim_resim.setText("")
        self.dikey_egim_2.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:12pt; color: #ffffff; font-family: Arial Black\">Yanal E\u011fim</span></p></body></html>", None))
        self.dikey_egim_deger_2.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:20pt; color: #ffffff; font-family: Arial Black\">12</span></p></body></html>", None))
        self.labelSolalt10.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt; font-family: Arial Black;  color: #ffffff\">10</span></p></body></html>", None))
        self.emniyet_kemeri.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:15pt; font-family: Arial Black; color: #ffffff;\">Emniyet Kemeri \u0130kaz Sistemi</span></p></body></html>", None))
        self.egim_kontrol.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt; font-family: Arial Black; color: #ffffff;\">E\u011fim Kontrol Sistemi</span></p></body></html>", None))
        self.LabelSolUst.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:11pt; color: #ffffff;\">Sol\u00dc</span></p></body></html>", None))
        self.labelSagUst.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:11pt; color: #ffffff;\">Sag\u00dc</span></p></body></html>", None))
        self.labelSolAlt.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:11pt; color: #ffffff;\">SolA</span></p></body></html>", None))
        self.labelSagAlt.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:11pt; color: #ffffff;\">SagA</span></p></body></html>", None))
        self.pushButtonGeri.setText(QCoreApplication.translate("MainWindow", u">>", None))
    # retranslateUi

