# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'oturma_egimLiffHk.ui'
##
## Created by: Qt User Interface Compiler version 6.1.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1200, 800)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.anaFrame = QFrame(self.centralwidget)
        self.anaFrame.setObjectName(u"anaFrame")
        self.anaFrame.setStyleSheet(u"background-color: rgb(6, 6, 58);")
        self.anaFrame.setFrameShape(QFrame.StyledPanel)
        self.anaFrame.setFrameShadow(QFrame.Raised)
        self.aracAnaFrame = QFrame(self.anaFrame)
        self.aracAnaFrame.setObjectName(u"aracAnaFrame")
        self.aracAnaFrame.setGeometry(QRect(0, 100, 500, 650))
        self.aracAnaFrame.setFrameShape(QFrame.StyledPanel)
        self.aracAnaFrame.setFrameShadow(QFrame.Raised)
        self.arac = QLabel(self.aracAnaFrame)
        self.arac.setObjectName(u"arac")
        self.arac.setGeometry(QRect(0, 10, 550, 700))
        self.arac.setPixmap(QPixmap(u"kobra\u00fcst.png"))
        self.arac.setScaledContents(True)
        self.onKoltukSol = QLabel(self.aracAnaFrame)
        self.onKoltukSol.setObjectName(u"onKoltukSol")
        self.onKoltukSol.setGeometry(QRect(175, 320, 55, 55))
        self.onKoltukSol.setPixmap(QPixmap(u"yesilkoltuk1.png"))
        self.onKoltukSol.setScaledContents(True)
        self.onKoltukSag = QLabel(self.aracAnaFrame)
        self.onKoltukSag.setObjectName(u"onKoltukSag")
        self.onKoltukSag.setGeometry(QRect(320, 320, 55, 55))
        self.onKoltukSag.setPixmap(QPixmap(u"k\u0131rm\u0131z\u0131koltuk1.png"))
        self.onKoltukSag.setScaledContents(True)
        self.koltuk1 = QLabel(self.aracAnaFrame)
        self.koltuk1.setObjectName(u"koltuk1")
        self.koltuk1.setGeometry(QRect(175, 395, 45, 45))
        self.koltuk1.setPixmap(QPixmap(u"k\u0131rm\u0131z\u0131koltuk1.png"))
        self.koltuk1.setScaledContents(True)
        self.koltuk2 = QLabel(self.aracAnaFrame)
        self.koltuk2.setObjectName(u"koltuk2")
        self.koltuk2.setGeometry(QRect(175, 450, 45, 45))
        self.koltuk2.setPixmap(QPixmap(u"k\u0131rm\u0131z\u0131koltuk1.png"))
        self.koltuk2.setScaledContents(True)
        self.koltuk3 = QLabel(self.aracAnaFrame)
        self.koltuk3.setObjectName(u"koltuk3")
        self.koltuk3.setGeometry(QRect(175, 510, 45, 45))
        self.koltuk3.setPixmap(QPixmap(u"yesilkoltuk1.png"))
        self.koltuk3.setScaledContents(True)
        self.koltuk4 = QLabel(self.aracAnaFrame)
        self.koltuk4.setObjectName(u"koltuk4")
        self.koltuk4.setGeometry(QRect(330, 395, 45, 45))
        self.koltuk4.setPixmap(QPixmap(u"beyaz1.png"))
        self.koltuk4.setScaledContents(True)
        self.koltuk5 = QLabel(self.aracAnaFrame)
        self.koltuk5.setObjectName(u"koltuk5")
        self.koltuk5.setGeometry(QRect(330, 450, 45, 45))
        self.koltuk5.setPixmap(QPixmap(u"yesilkoltuk1.png"))
        self.koltuk5.setScaledContents(True)
        self.koltuk6 = QLabel(self.aracAnaFrame)
        self.koltuk6.setObjectName(u"koltuk6")
        self.koltuk6.setGeometry(QRect(330, 510, 45, 45))
        self.koltuk6.setPixmap(QPixmap(u"yesilkoltuk1.png"))
        self.koltuk6.setScaledContents(True)
        self.koltukKule = QLabel(self.aracAnaFrame)
        self.koltukKule.setObjectName(u"koltukKule")
        self.koltukKule.setGeometry(QRect(252, 420, 45, 45))
        self.koltukKule.setPixmap(QPixmap(u"k\u0131rm\u0131z\u0131koltuk1.png"))
        self.koltukKule.setScaledContents(True)
        self.egimAnaFrame = QFrame(self.anaFrame)
        self.egimAnaFrame.setObjectName(u"egimAnaFrame")
        self.egimAnaFrame.setGeometry(QRect(575, 155, 600, 600))
        self.egimAnaFrame.setStyleSheet(u"background-color: rgb(170, 255, 255);\n"
"\n"
"background-color: rgb(6, 6, 58);\n"
"")
        self.egimAnaFrame.setFrameShape(QFrame.StyledPanel)
        self.egimAnaFrame.setFrameShadow(QFrame.Raised)
        self.egimGradient = QFrame(self.egimAnaFrame)
        self.egimGradient.setObjectName(u"egimGradient")
        self.egimGradient.setGeometry(QRect(50, 50, 500, 500))
        self.egimGradient.setStyleSheet(u"background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.526, y2:0.988636, stop:0 rgba(254, 124, 0, 255), stop:1 rgba(108, 1, 175, 255));\n"
"border-radius: 250px;")
        self.egimGradient.setFrameShape(QFrame.StyledPanel)
        self.egimGradient.setFrameShadow(QFrame.Raised)
        self.egimFrame1 = QFrame(self.egimAnaFrame)
        self.egimFrame1.setObjectName(u"egimFrame1")
        self.egimFrame1.setGeometry(QRect(60, 60, 480, 480))
        self.egimFrame1.setStyleSheet(u"border-radius: 240px;\n"
"background-color: rgb(3, 2, 34);")
        self.egimFrame1.setFrameShape(QFrame.StyledPanel)
        self.egimFrame1.setFrameShadow(QFrame.Raised)
        self.egimFrame2 = QFrame(self.egimAnaFrame)
        self.egimFrame2.setObjectName(u"egimFrame2")
        self.egimFrame2.setGeometry(QRect(90, 90, 420, 420))
        self.egimFrame2.setStyleSheet(u"border-radius: 210px;\n"
"background-color: rgb(6, 6, 58);")
        self.egimFrame2.setFrameShape(QFrame.StyledPanel)
        self.egimFrame2.setFrameShadow(QFrame.Raised)
        self.yanal_egim = QLabel(self.egimFrame2)
        self.yanal_egim.setObjectName(u"yanal_egim")
        self.yanal_egim.setGeometry(QRect(110, 160, 120, 40))
        self.yanal_egim.setAlignment(Qt.AlignCenter)
        self.yanal_egim_deger = QLabel(self.egimFrame2)
        self.yanal_egim_deger.setObjectName(u"yanal_egim_deger")
        self.yanal_egim_deger.setGeometry(QRect(220, 160, 120, 40))
        self.yanal_egim_deger.setAlignment(Qt.AlignCenter)
        self.yanal_egim_resim = QLabel(self.egimFrame2)
        self.yanal_egim_resim.setObjectName(u"yanal_egim_resim")
        self.yanal_egim_resim.setGeometry(QRect(135, 0, 160, 160))
        self.yanal_egim_resim.setStyleSheet(u"background-color: none;")
        self.yanal_egim_resim.setPixmap(QPixmap(u"kobra\u00f6n.png"))
        self.yanal_egim_resim.setScaledContents(True)
        self.yanal_egim_resim.setMargin(-40)
        self.dikey_egim_resim = QLabel(self.egimFrame2)
        self.dikey_egim_resim.setObjectName(u"dikey_egim_resim")
        self.dikey_egim_resim.setGeometry(QRect(110, 180, 200, 200))
        self.dikey_egim_resim.setStyleSheet(u"background-color: none;")
        self.dikey_egim_resim.setPixmap(QPixmap(u"kobrayan.png"))
        self.dikey_egim_resim.setScaledContents(True)
        self.dikey_egim_resim.setMargin(-1)
        self.dikey_egim_deger = QLabel(self.egimFrame2)
        self.dikey_egim_deger.setObjectName(u"dikey_egim_deger")
        self.dikey_egim_deger.setGeometry(QRect(220, 360, 120, 40))
        self.dikey_egim_deger.setStyleSheet(u"background-color: none;")
        self.dikey_egim_deger.setAlignment(Qt.AlignCenter)
        self.dikey_egim = QLabel(self.egimFrame2)
        self.dikey_egim.setObjectName(u"dikey_egim")
        self.dikey_egim.setGeometry(QRect(100, 360, 120, 40))
        self.dikey_egim.setStyleSheet(u"background-color: none;")
        self.dikey_egim.setAlignment(Qt.AlignCenter)
        self.labelSolust10 = QLabel(self.egimAnaFrame)
        self.labelSolust10.setObjectName(u"labelSolust10")
        self.labelSolust10.setGeometry(QRect(15, 180, 40, 40))
        self.labelSolust10.setStyleSheet(u"background-color: transparent;")
        self.labelSolust10.setAlignment(Qt.AlignCenter)
        self.yatayCizgi = QFrame(self.egimAnaFrame)
        self.yatayCizgi.setObjectName(u"yatayCizgi")
        self.yatayCizgi.setGeometry(QRect(0, 280, 600, 40))
        self.yatayCizgi.setStyleSheet(u"background-color: rgb(6, 6, 58);")
        self.yatayCizgi.setFrameShape(QFrame.StyledPanel)
        self.yatayCizgi.setFrameShadow(QFrame.Raised)
        self.kirmizi = QFrame(self.yatayCizgi)
        self.kirmizi.setObjectName(u"kirmizi")
        self.kirmizi.setGeometry(QRect(75, 15, 450, 10))
        self.kirmizi.setStyleSheet(u"background-color: rgb(255, 0, 0);")
        self.kirmizi.setFrameShape(QFrame.StyledPanel)
        self.kirmizi.setFrameShadow(QFrame.Raised)
        self.eksi = QLabel(self.yatayCizgi)
        self.eksi.setObjectName(u"eksi")
        self.eksi.setGeometry(QRect(30, 0, 40, 40))
        self.eksi.setAlignment(Qt.AlignCenter)
        self.arti = QLabel(self.yatayCizgi)
        self.arti.setObjectName(u"arti")
        self.arti.setGeometry(QRect(530, 0, 40, 40))
        self.arti.setAlignment(Qt.AlignCenter)
        self.dikeyCizgi = QFrame(self.egimAnaFrame)
        self.dikeyCizgi.setObjectName(u"dikeyCizgi")
        self.dikeyCizgi.setGeometry(QRect(280, 0, 40, 600))
        self.dikeyCizgi.setStyleSheet(u"background-color: rgb(6, 6, 58);")
        self.dikeyCizgi.setFrameShape(QFrame.StyledPanel)
        self.dikeyCizgi.setFrameShadow(QFrame.Raised)
        self.labelSolust20 = QLabel(self.egimAnaFrame)
        self.labelSolust20.setObjectName(u"labelSolust20")
        self.labelSolust20.setGeometry(QRect(60, 100, 40, 40))
        self.labelSolust20.setStyleSheet(u"background-color: transparent;")
        self.labelSolust20.setAlignment(Qt.AlignCenter)
        self.labelSolust30 = QLabel(self.egimAnaFrame)
        self.labelSolust30.setObjectName(u"labelSolust30")
        self.labelSolust30.setGeometry(QRect(140, 40, 40, 40))
        self.labelSolust30.setStyleSheet(u"background-color: transparent;")
        self.labelSolust30.setAlignment(Qt.AlignCenter)
        self.labelSolust40 = QLabel(self.egimAnaFrame)
        self.labelSolust40.setObjectName(u"labelSolust40")
        self.labelSolust40.setGeometry(QRect(240, 10, 40, 40))
        self.labelSolust40.setStyleSheet(u"background-color: transparent;")
        self.labelSolust40.setAlignment(Qt.AlignCenter)
        self.labelSagust10 = QLabel(self.egimAnaFrame)
        self.labelSagust10.setObjectName(u"labelSagust10")
        self.labelSagust10.setGeometry(QRect(545, 180, 40, 40))
        self.labelSagust10.setStyleSheet(u"background-color: transparent;")
        self.labelSagust10.setAlignment(Qt.AlignCenter)
        self.labelSagust20 = QLabel(self.egimAnaFrame)
        self.labelSagust20.setObjectName(u"labelSagust20")
        self.labelSagust20.setGeometry(QRect(500, 100, 40, 40))
        self.labelSagust20.setStyleSheet(u"background-color: transparent;")
        self.labelSagust20.setAlignment(Qt.AlignCenter)
        self.labelSagust30 = QLabel(self.egimAnaFrame)
        self.labelSagust30.setObjectName(u"labelSagust30")
        self.labelSagust30.setGeometry(QRect(420, 40, 40, 40))
        self.labelSagust30.setStyleSheet(u"background-color: transparent;")
        self.labelSagust30.setAlignment(Qt.AlignCenter)
        self.labelSagust40 = QLabel(self.egimAnaFrame)
        self.labelSagust40.setObjectName(u"labelSagust40")
        self.labelSagust40.setGeometry(QRect(320, 10, 40, 40))
        self.labelSagust40.setStyleSheet(u"background-color: transparent;")
        self.labelSagust40.setAlignment(Qt.AlignCenter)
        self.labelSolalt60 = QLabel(self.egimAnaFrame)
        self.labelSolalt60.setObjectName(u"labelSolalt60")
        self.labelSolalt60.setGeometry(QRect(250, 555, 40, 40))
        self.labelSolalt60.setStyleSheet(u"background-color: transparent;")
        self.labelSolalt60.setAlignment(Qt.AlignCenter)
        self.labelSagalt60 = QLabel(self.egimAnaFrame)
        self.labelSagalt60.setObjectName(u"labelSagalt60")
        self.labelSagalt60.setGeometry(QRect(310, 555, 40, 40))
        self.labelSagalt60.setStyleSheet(u"background-color: transparent;")
        self.labelSagalt60.setAlignment(Qt.AlignCenter)
        self.labelSolalt10 = QLabel(self.egimAnaFrame)
        self.labelSolalt10.setObjectName(u"labelSolalt10")
        self.labelSolalt10.setGeometry(QRect(10, 320, 40, 40))
        self.labelSolalt10.setStyleSheet(u"background-color: transparent;")
        self.labelSolalt10.setAlignment(Qt.AlignCenter)
        self.labelSolalt20 = QLabel(self.egimAnaFrame)
        self.labelSolalt20.setObjectName(u"labelSolalt20")
        self.labelSolalt20.setGeometry(QRect(20, 380, 40, 40))
        self.labelSolalt20.setStyleSheet(u"background-color: transparent;")
        self.labelSolalt20.setAlignment(Qt.AlignCenter)
        self.labelSolalt30 = QLabel(self.egimAnaFrame)
        self.labelSolalt30.setObjectName(u"labelSolalt30")
        self.labelSolalt30.setGeometry(QRect(50, 440, 40, 40))
        self.labelSolalt30.setStyleSheet(u"background-color: transparent;")
        self.labelSolalt30.setAlignment(Qt.AlignCenter)
        self.labelSolalt40 = QLabel(self.egimAnaFrame)
        self.labelSolalt40.setObjectName(u"labelSolalt40")
        self.labelSolalt40.setGeometry(QRect(85, 490, 40, 40))
        self.labelSolalt40.setStyleSheet(u"background-color: transparent;")
        self.labelSolalt40.setAlignment(Qt.AlignCenter)
        self.labelSolalt50 = QLabel(self.egimAnaFrame)
        self.labelSolalt50.setObjectName(u"labelSolalt50")
        self.labelSolalt50.setGeometry(QRect(155, 530, 40, 40))
        self.labelSolalt50.setStyleSheet(u"background-color: transparent;")
        self.labelSolalt50.setAlignment(Qt.AlignCenter)
        self.labelSagalt50 = QLabel(self.egimAnaFrame)
        self.labelSagalt50.setObjectName(u"labelSagalt50")
        self.labelSagalt50.setGeometry(QRect(385, 540, 40, 40))
        self.labelSagalt50.setStyleSheet(u"background-color: transparent;")
        self.labelSagalt50.setAlignment(Qt.AlignCenter)
        self.labelSagalt40 = QLabel(self.egimAnaFrame)
        self.labelSagalt40.setObjectName(u"labelSagalt40")
        self.labelSagalt40.setGeometry(QRect(445, 510, 40, 40))
        self.labelSagalt40.setStyleSheet(u"background-color: transparent;")
        self.labelSagalt40.setAlignment(Qt.AlignCenter)
        self.labelSagalt30 = QLabel(self.egimAnaFrame)
        self.labelSagalt30.setObjectName(u"labelSagalt30")
        self.labelSagalt30.setGeometry(QRect(500, 460, 40, 40))
        self.labelSagalt30.setStyleSheet(u"background-color: transparent;")
        self.labelSagalt30.setAlignment(Qt.AlignCenter)
        self.labelSagalt20 = QLabel(self.egimAnaFrame)
        self.labelSagalt20.setObjectName(u"labelSagalt20")
        self.labelSagalt20.setGeometry(QRect(535, 400, 40, 40))
        self.labelSagalt20.setStyleSheet(u"background-color: transparent;")
        self.labelSagalt20.setAlignment(Qt.AlignCenter)
        self.labelSagalt10 = QLabel(self.egimAnaFrame)
        self.labelSagalt10.setObjectName(u"labelSagalt10")
        self.labelSagalt10.setGeometry(QRect(548, 340, 40, 40))
        self.labelSagalt10.setStyleSheet(u"background-color: transparent;")
        self.labelSagalt10.setAlignment(Qt.AlignCenter)
        self.solustProgress = QFrame(self.egimAnaFrame)
        self.solustProgress.setObjectName(u"solustProgress")
        self.solustProgress.setGeometry(QRect(70, 70, 230, 230))
        self.solustProgress.setStyleSheet(u"\n"
"background-color: qconicalgradient(cx:1, cy:0.999, angle:180, stop:0.830928 rgba(85, 170, 255, 0), stop:0.83299 rgba(252, 201, 109, 255));\n"
"background-color: qconicalgradient(cx:1, cy:1, angle:180, stop:0.9027 rgba(85, 170, 255, 0), stop:0.903955 rgba(252, 201, 109, 255));\n"
"border-top-left-radius: 230px;")
        self.solustProgress.setFrameShape(QFrame.StyledPanel)
        self.solustProgress.setFrameShadow(QFrame.Raised)
        self.sagustProgress = QFrame(self.egimAnaFrame)
        self.sagustProgress.setObjectName(u"sagustProgress")
        self.sagustProgress.setGeometry(QRect(300, 70, 230, 230))
        self.sagustProgress.setStyleSheet(u"background-color: qconicalgradient(cx:0, cy:1, angle:0, stop:0.1060452 rgba(252, 201, 109, 255), stop:0.107345 rgba(85, 170, 255, 0));\n"
"border-top-right-radius: 230px;")
        self.sagustProgress.setFrameShape(QFrame.StyledPanel)
        self.sagustProgress.setFrameShadow(QFrame.Raised)
        self.solaltProgress = QFrame(self.egimAnaFrame)
        self.solaltProgress.setObjectName(u"solaltProgress")
        self.solaltProgress.setGeometry(QRect(70, 300, 230, 230))
        self.solaltProgress.setStyleSheet(u"background-color: qconicalgradient(cx:1, cy:0, angle:180, stop:0.112345 rgba(252, 201, 109, 255), stop:0.112994 rgba(85, 170, 255, 0));\n"
"border-bottom-left-radius: 230px;")
        self.solaltProgress.setFrameShape(QFrame.StyledPanel)
        self.solaltProgress.setFrameShadow(QFrame.Raised)
        self.sagaltProgress = QFrame(self.egimAnaFrame)
        self.sagaltProgress.setObjectName(u"sagaltProgress")
        self.sagaltProgress.setGeometry(QRect(300, 300, 230, 230))
        self.sagaltProgress.setStyleSheet(u"\n"
"background-color: qconicalgradient(cx:1, cy:1, angle:180.045, stop:0.835227 rgba(85, 170, 255, 0), stop:0.840909 rgba(252, 201, 109, 255));\n"
"background-color: qconicalgradient(cx:0, cy:0, angle:0.3, stop:0.835227 rgba(85, 170, 255, 0), stop:0.835909 rgba(252, 201, 109, 255));\n"
"background-color: qconicalgradient(cx:0, cy:0, angle:0, stop:0.740113 rgba(85, 170, 255, 0), stop:0.751412 rgba(252, 201, 109, 255));\n"
"border-bottom-right-radius: 230px;")
        self.sagaltProgress.setFrameShape(QFrame.StyledPanel)
        self.sagaltProgress.setFrameShadow(QFrame.Raised)
        self.progressGolge = QFrame(self.egimAnaFrame)
        self.progressGolge.setObjectName(u"progressGolge")
        self.progressGolge.setGeometry(QRect(85, 85, 430, 430))
        self.progressGolge.setStyleSheet(u"background-color: rgba(0, 0, 0,150);\n"
"border-radius: 215px;\n"
"border-width: 2px;\n"
"border-style: solid;")
        self.progressGolge.setFrameShape(QFrame.StyledPanel)
        self.progressGolge.setFrameShadow(QFrame.Raised)
        self.egimGradient.raise_()
        self.egimFrame1.raise_()
        self.labelSolust10.raise_()
        self.labelSolust20.raise_()
        self.labelSolust30.raise_()
        self.labelSolust40.raise_()
        self.labelSagust10.raise_()
        self.labelSagust20.raise_()
        self.labelSagust30.raise_()
        self.labelSagust40.raise_()
        self.labelSolalt60.raise_()
        self.labelSolalt10.raise_()
        self.labelSolalt20.raise_()
        self.labelSolalt30.raise_()
        self.labelSolalt40.raise_()
        self.labelSolalt50.raise_()
        self.labelSagalt50.raise_()
        self.labelSagalt20.raise_()
        self.labelSagalt10.raise_()
        self.solustProgress.raise_()
        self.sagustProgress.raise_()
        self.solaltProgress.raise_()
        self.sagaltProgress.raise_()
        self.progressGolge.raise_()
        self.dikeyCizgi.raise_()
        self.egimFrame2.raise_()
        self.yatayCizgi.raise_()
        self.labelSagalt40.raise_()
        self.labelSagalt30.raise_()
        self.labelSagalt60.raise_()
        self.emniyet_kemeri = QLabel(self.anaFrame)
        self.emniyet_kemeri.setObjectName(u"emniyet_kemeri")
        self.emniyet_kemeri.setGeometry(QRect(50, 50, 500, 50))
        self.emniyet_kemeri.setAlignment(Qt.AlignCenter)
        self.egim_kontrol = QLabel(self.anaFrame)
        self.egim_kontrol.setObjectName(u"egim_kontrol")
        self.egim_kontrol.setGeometry(QRect(625, 50, 500, 50))
        self.egim_kontrol.setAlignment(Qt.AlignCenter)
        self.horizontalSliderYanal = QSlider(self.anaFrame)
        self.horizontalSliderYanal.setObjectName(u"horizontalSliderYanal")
        self.horizontalSliderYanal.setGeometry(QRect(620, 760, 160, 18))
        self.horizontalSliderYanal.setOrientation(Qt.Horizontal)
        self.horizontalSliderDikey = QSlider(self.anaFrame)
        self.horizontalSliderDikey.setObjectName(u"horizontalSliderDikey")
        self.horizontalSliderDikey.setGeometry(QRect(1000, 760, 160, 18))
        self.horizontalSliderDikey.setOrientation(Qt.Horizontal)

        self.verticalLayout.addWidget(self.anaFrame)

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.arac.setText("")
        self.onKoltukSol.setText("")
        self.onKoltukSag.setText("")
        self.koltuk1.setText("")
        self.koltuk2.setText("")
        self.koltuk3.setText("")
        self.koltuk4.setText("")
        self.koltuk5.setText("")
        self.koltuk6.setText("")
        self.koltukKule.setText("")
        self.yanal_egim.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:12pt; color: #ffffff; font-family: Arial Black\">Yanal E\u011fim</span></p></body></html>", None))
        self.yanal_egim_deger.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:20pt; color: #ffffff; font-family: Arial Black\">10</span></p></body></html>", None))
        self.yanal_egim_resim.setText("")
        self.dikey_egim_resim.setText("")
        self.dikey_egim_deger.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:20pt; color: #ffffff; font-family: Arial Black\">10</span></p></body></html>", None))
        self.dikey_egim.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:12pt; color: #ffffff; font-family: Arial Black\">Dikey E\u011fim</span></p></body></html>", None))
        self.labelSolust10.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt; font-family: Arial Black;  color: #ffffff\">10</span></p></body></html>", None))
        self.eksi.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:22pt; color: #ffffff; font-family: Arial Black\">-</span></p></body></html>", None))
        self.arti.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:22pt; color: #ffffff; font-family: Arial Black\">+</span></p></body></html>", None))
        self.labelSolust20.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt; font-family: Arial Black;  color: #ffffff\">20</span></p></body></html>", None))
        self.labelSolust30.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt; font-family: Arial Black;  color: #ffffff\">30</span></p></body></html>", None))
        self.labelSolust40.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt; font-family: Arial Black;  color: #ff0000\">40</span></p></body></html>", None))
        self.labelSagust10.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt; font-family: Arial Black;  color: #ffffff\">10</span></p></body></html>", None))
        self.labelSagust20.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt; font-family: Arial Black;  color: #ffffff\">20</span></p></body></html>", None))
        self.labelSagust30.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt; font-family: Arial Black;  color: #ffffff\">30</span></p></body></html>", None))
        self.labelSagust40.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt; font-family: Arial Black;  color: #ff0000\">40</span></p></body></html>", None))
        self.labelSolalt60.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt; font-family: Arial Black;  color: #ff0000\">60</span></p></body></html>", None))
        self.labelSagalt60.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt; font-family: Arial Black;  color: #ff0000\">60</span></p></body></html>", None))
        self.labelSolalt10.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt; font-family: Arial Black;  color: #ffffff\">10</span></p></body></html>", None))
        self.labelSolalt20.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt; font-family: Arial Black;  color: #ffffff\">20</span></p></body></html>", None))
        self.labelSolalt30.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt; font-family: Arial Black;  color: #ffffff\">30</span></p></body></html>", None))
        self.labelSolalt40.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt; font-family: Arial Black;  color: #ffffff\">40</span></p></body></html>", None))
        self.labelSolalt50.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt; font-family: Arial Black;  color: #ffffff\">50</span></p></body></html>", None))
        self.labelSagalt50.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt; font-family: Arial Black;  color: #ffffff\">50</span></p></body></html>", None))
        self.labelSagalt40.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt; font-family: Arial Black;  color: #ffffff\">40</span></p></body></html>", None))
        self.labelSagalt30.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt; font-family: Arial Black;  color: #ffffff\">30</span></p></body></html>", None))
        self.labelSagalt20.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt; font-family: Arial Black;  color: #ffffff\">20</span></p></body></html>", None))
        self.labelSagalt10.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt; font-family: Arial Black;  color: #ffffff\">10</span></p></body></html>", None))
        self.emniyet_kemeri.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt; font-family: Arial Black; color: #ffffff;\">Emniyet Kemeri \u0130kaz Sistemi</span></p></body></html>", None))
        self.egim_kontrol.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt; font-family: Arial Black; color: #ffffff;\">E\u011fim Kontrol Sistemi</span></p></body></html>", None))
    # retranslateUi

